function m(b,a,c,d){b.j.tb(b.wb,a,c,d)}function n(b,a,c,d){b.j.fa?m(b,a,c,d):b.j.af()._OnMessageFromDOM({type:"event",component:b.wb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.j.B(b.wb,a,c)}function v(b,a){for(const [c,d]of a)p(b,c,d)}function w(b){b.cc||(b.j.Hc(b.re),b.cc=!0)}window.ga=class{constructor(b,a){this.j=b;this.wb=a;this.cc=!1;this.re=()=>this.Ia()}Ad(){}Ia(){}};
window.Mf=class{constructor(){this.vd=-1}l(){-1!==this.vd&&(self.clearTimeout(this.vd),this.vd=-1)}};"use strict";class aa{constructor(b){this.zb=b;this.ad=!1;this.jd=!0;this.Bb=this.ua=this.wd=-1}}
function ba(b,a){const c=a.elementId,d=b.nb(c,a),e=new aa(d);b.Oa.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.jd=!!a.isVisible;var f=b.Kc(d);f.addEventListener("focus",()=>{x(b,"elem-focused",c)});f.addEventListener("blur",()=>{x(b,"elem-blurred",c)});f=a.htmlIndex;e.wd=f;e.Bb=a.htmlZIndex;b.Ya&&(a=b.j.zc(f),e.ua=a,b.j.Qb(a).appendChild(d))}function y(b,a,c){p(b,a,d=>{const e=z(b,d.elementId);return c(e,d)})}
function z(b,a){b=b.Oa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.zb}function x(b,a,c,d){d||(d={});d.elementId=c;m(b,a,d)}function A(b,a,c,d){d||(d={});d.elementId=c;n(b,a,d)}
window.Ta=class extends self.ga{constructor(b,a){super(b,a);this.Oa=new Map;this.Ya=!0;v(this,[["create",c=>ba(this,c)],["destroy",c=>{c=c.elementId;const d=z(this,c);this.Ya&&d.parentElement.removeChild(d);this.Oa.delete(c)}],["set-visible",c=>{if(this.Ya){var d=this.Oa.get(c.elementId),e=d.zb;d.ad?e.style.display=c.isVisible?"":"none":d.jd=!!c.isVisible}}],["update-position",c=>{if(this.Ya){var d=this.Oa.get(c.elementId),e=d.zb,f=this.j;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=
c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.wd=g;g=f.zc(g);g!==d.ua&&(e.remove(),f.Qb(g).appendChild(e),d.ua=g,f.Vc());c=c.htmlZIndex;c!==d.Bb&&(d.Bb=c,f.Vc());d.ad||(d.ad=!0,d.jd&&(e.style.display=""))}}],["update-state",c=>{const d=z(this,c.elementId);this.sa(d,c)}],["focus",c=>this.Sc(c)],["set-css-style",c=>{const d=z(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",
c=>{z(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{z(this,c.elementId).removeAttribute(c.name)}]]);y(this,"get-element",c=>c)}nb(){throw Error("required override");}sa(){throw Error("required override");}Kc(b){return b}Sc(b){const a=this.Kc(z(this,b.elementId));b.focus?a.focus():a.blur()}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),da=/android/i.test(navigator.userAgent);let ea=0;
function fa(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Cf?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.Gf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ha(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let B=new Audio;
const ia={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}
function ka(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const la=[];let C=0;window.RealFile=window.File;const D=[],ma=new Map,na=new Map;let oa=0;const pa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");pa.push(b)};const qa=new Set(["cordova","playable-ad","instant-games"]);let ra=!1;
window.L=class b{constructor(a){this.fa=a.If;this.Ca=null;this.ca="";this.ib=a.Ff;this.Ob={};this.bb=this.za=null;this.$a=[];this.pa=null;this.de=!0;this.N=[];this.pd=[];this.qd=!1;this.se=()=>this.Ze();this.ed=!1;this.Yd=0;this.Db=null;this.hb=-1;this.yf=()=>this.kf();this.Lb=new Set;this.xd=null;this.te=[];this.u=a.ue;this.dc="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.fa=!1;if("cordova"===this.u&&this.fa&&da){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.fa=!1)}this.ra()?self.chrome.webview.addEventListener("message",c=>this.Od(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Od(c));this.hc=this.wa=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.pf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.ef());this.B("runtime","cordova-fetch-local-file",c=>this.ff(c));this.B("runtime","create-job-worker",()=>this.gf());this.B("runtime","send-wrapper-extension-message",c=>this.nf(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.Ub(a)):this.Ub(a)}l(){this.Ic();this.Ca&&(this.Ca=this.Ca.onmessage=null);this.za&&(this.za.terminate(),this.za=null);this.bb&&(this.bb.l(),this.bb=null);for(const {canvas:a,
lb:c}of this.N)a.remove(),c.remove();this.N.length=0}Fd(){return this.N[0].canvas}zc(a){return Math.min(a,this.N.length-1)}Qb(a){if(0>a||a>=this.N.length)throw new RangeError("invalid canvas layer");return this.N[a].lb}Pe(){return ca&&"cordova"===this.u}rb(){const a=navigator.userAgent;return ca&&qa.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Ne(){return da}Gd(){return da&&qa.has(this.u)}Id(){return"windows-webview2"===this.u||!!("preview"===this.u&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}ra(){return this.Id()||"xbox-uwp-webview2"===this.u}async Ub(a){this.fa&&!await ha()&&(this.fa=!1);"macos-wkwebview"===this.u?this.Ka({type:"ready"}):this.ra()&&(this.rf(),this.te=(await this.df()).registeredComponentIds);if("playable-ad"===this.u){this.wa=self.c3_base64files;this.hc={};await this.We();for(let d=0,e=a.kb.length;d<e;++d){var c=a.kb[d];this.hc.hasOwnProperty(c)?a.kb[d]={Cf:!0,Gf:this.hc[c]}:this.wa.hasOwnProperty(c)&&(a.kb[d]=URL.createObjectURL(this.wa[c]))}a.wc=
[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Hc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Ef?this.ca=a.Ef:(c=location.origin,this.ca=("null"===c?"file:///":c)+location.pathname,c=this.ca.lastIndexOf("/"),-1!==c&&(this.ca=this.ca.substr(0,c+1)));a.Kf&&(this.Ob=a.Kf);c=new MessageChannel;this.Ca=c.port1;this.Ca.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.jf(d));this.Db=
new self.Qe(this);await sa(this.Db);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.fa?await this.cf(a,c.port2):await this.bf(a,c.port2)}Lc(a){a=this.Ob.hasOwnProperty(a)?this.Ob[a]:a.endsWith("/workermain.js")&&this.Ob.hasOwnProperty("workermain.js")?this.Ob["workermain.js"]:"playable-ad"===
this.u&&this.wa.hasOwnProperty(a)?this.wa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async yc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.dc)return a=await this.Pb(d.Bf?a:this.ib+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}ta(){return Math.max(window.innerWidth,1)}ja(){return Math.max(window.innerHeight,1)}Md(a){var c=this.ca,d=location.href,e=this.ta(),f=this.ja(),g=window.devicePixelRatio,h=b.qb(),k=a.Qf,l=window.cr_previewImageBlobs||this.wa,q=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.ue;var u=(new URLSearchParams(self.location.search)).has("debug"),E=this.Db;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:q,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Pf,jobScheduler:{inputPort:E.dd,outputPort:E.od,maxNumWorkers:E.vf},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ib+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ib+"opus.wasm.wasm",isFileProtocol:this.dc,isiOSCordova:this.Pe(),isiOSWebView:this.rb(),isWindowsWebView2:this.Id(),isAnyWebView2Wrapper:this.ra(),wrapperComponentIds:this.te,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async cf(a,c){const d=this.Lc(a.Jf);"preview"===this.u?(this.za=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,q)=>{const r=t=>{this.za.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():q()};this.za.addEventListener("message",r);this.za.postMessage({type:"construct-worker-init","import":(new URL(d,this.ca)).toString()})})):this.za=await this.yc(d,this.ca,{type:"module",name:"Runtime",Bf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.N.push({canvas:e,lb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.wc||[],k=a.kb;h=await Promise.all(h.map(l=>this.Wa(l)));k=await Promise.all(k.map(l=>this.Wa(l)));if("cordova"===this.u)for(let l=0,q=a.vc.length;l<q;++l){const r=
a.vc[l],t=r[0];if(t===a.yd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Wa(t)}this.za.postMessage(Object.assign(this.Md(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.vc,mainProjectScript:a.yd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...ta(this.Db)]);this.$a=D.map(l=>new l(this));this.Ld();ua(e);va(g);wa(this.pa);self.c3_callFunction=(l,q)=>{var r=this.pa;return r.j.Jd(r.wb,"js-invoke-function",
{name:l,params:q})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.tb("runtime","go-to-last-error-script"))}async bf(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.N.push({canvas:d,lb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.$a=D.map(h=>new h(this));this.Ld();ua(d);va(e);e=a.kb.map(h=>"string"===
typeof h?(new URL(h,this.ca)).toString():h);if(Array.isArray(a.wc)){var f=[...a.wc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Wa(h)));await Promise.all(e.map(h=>fa(h)));e=self.C3_ProjectScriptsStatus;f=a.yd;const g=a.vc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Wa(k),await fa(k),"preview"!==this.u||e[h]||this.Qd(h,"main script did not run to completion")}catch(l){this.Qd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Wa(k),await fa(k);"preview"===this.u&&"object"!==typeof self.Lf.Nf?(this.Xb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Md(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:pa}),wa(this.pa),this.Nd(),this.bb=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.bb,
a))}Qd(a,c){this.Xb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Nd(){this.Xb()}Xb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async gf(){const a=await za(this.Db);return{outputPort:a,transferables:[a]}}pf(a){if(!this.ed){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,lb:h}of this.N)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.de&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.de=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.N.length)for(;this.N.length>c;){const {canvas:l,lb:q}=this.N.pop();q.remove();this.fa&&!d?this.pd.push(l):l.remove()}else if(c>this.N.length)for(let l=0,q=c-this.N.length;l<q;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.fa?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,ua(c),va(d),this.N.push({canvas:c,lb:d});for(const l of this.$a)if(l instanceof window.Ta&&l.Ya)for(const q of l.Oa.values())e=l.j.zc(q.wd),f=q.ua,-1!==e&&-1!==f&&e!==f&&(f=q.zb,f.remove(),l.j.Qb(e).appendChild(f),q.ua=e);this.Vc();return{addedCanvases:a,transferables:k}}ef(){for(const a of this.pd)a.remove();this.pd.length=0}Vc(){this.qd||(this.qd=!0,this.Hc(this.se))}Ze(){this.Pd(this.se);
this.qd=!1;let a=[];for(var c of this.$a)if(c instanceof window.Ta){var d=c.Ya?[...c.Oa.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.ua,l=h.ua;return k!==l?k-l:g.Bb-h.Bb});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.ua!==c&&(this.Kd(c,a.slice(d,e)),c=g.ua,d=e)}d<e&&this.Kd(c,a.slice(d,e))}Kd(a,c){if(!(1>=c.length||a>=this.N.length)){c=c.map(k=>k.zb);var d=new Set(c);a=this.Qb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}af(){if(this.fa)throw Error("not available in worker mode");return this.bb}tb(a,c,d,e,f){this.Ca.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}Jd(a,c,d,e,f){const g=oa++,h=new Promise((k,l)=>{na.set(g,{resolve:k,reject:l})});this.Ca.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.hf(a);if("result"===c)this.lf(a);else if("runtime-ready"===c)this.mf();else if("alert-error"===c)this.Xb(),alert(a.message);else if("creating-runtime"===c)this.Nd();else throw Error(`unknown message '${c}'`);}hf(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=ma.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Wb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Wb(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Wb(f,!1,""+h)}):this.Wb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Wb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.Ca.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}lf(a){const c=a.responseId,d=a.isOk;a=a.result;const e=na.get(c);d?e.resolve(a):e.reject(a);na.delete(c)}B(a,c,d){let e=ma.get(a);e||(e=new Map,ma.set(a,
e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Y(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}Ld(){for(const a of this.$a)if("runtime"===a.wb){this.pa=a;return}throw Error("cannot find runtime DOM handler");}jf(a){this.tb("debugger","message",a)}mf(){for(const a of this.$a)a.Ad()}static qb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ra)}static Yb(a){ra=!!a}Hc(a){this.Lb.add(a);
this.Uc()}Pd(a){this.Lb.delete(a);0===this.Lb.size&&this.Ic()}Uc(){-1===this.hb&&0<this.Lb.size&&(this.hb=requestAnimationFrame(this.yf))}Ic(){-1!==this.hb&&(cancelAnimationFrame(this.hb),this.hb=-1)}kf(){this.hb=-1;for(const a of this.Lb)a();this.Uc()}Ja(a){this.pa.Ja(a)}Va(a){this.pa.Va(a)}Tc(){this.pa.Tc()}Tb(a){this.pa.Tb(a)}Oe(){return!!ia["audio/webm; codecs=opus"]}async sf(a){a=await this.Jd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Se(a){this.ed=!0;this.Yd=
a}Me(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Hd(a){return!this.Me(a)}async Wa(a){return"cordova"===this.u&&(a.startsWith("file:")||this.dc&&this.Hd(a))?(a.startsWith(this.ca)&&(a=a.substr(this.ca.length)),a=await this.Pb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async ff(a){const c=a.filename;switch(a.as){case "text":return await this.Le(c);case "buffer":return await this.Pb(c);default:throw Error("unsupported type");
}}Dd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Le(a){a=await this.Dd(a);return await ja(a)}Jc(){if(la.length&&!(8<=C)){C++;var a=la.shift();this.Xe(a.filename,a.Hf,a.Af)}}Pb(a){return new Promise((c,d)=>{la.push({filename:a,Hf:e=>{C--;this.Jc();c(e)},Af:e=>{C--;this.Jc();d(e)}});this.Jc()})}async Xe(a,c,d){try{const e=await this.Dd(a),f=await ka(e);c(f)}catch(e){d(e)}}Od(a){if("entered-fullscreen"===
a)b.Yb(!0),F(this.pa);else if("exited-fullscreen"===a)b.Yb(!1),F(this.pa);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.xd(a),this.xd=null):"extension-message"===c?this.tb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}nf(a){this.Ka({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ka(a){this.ra()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}rf(){window.moveTo=(a,c)=>{this.Ka({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ka({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}df(){return this.ra()?new Promise(a=>{this.xd=a;this.Ka({type:"wrapper-init"})}):Promise.resolve()}async We(){const a=[];for(const [c,d]of Object.entries(this.wa))a.push(this.Ve(c,d));
await Promise.all(a)}async Ve(a,c){if("object"===typeof c)this.wa[a]=new Blob([c.str],{type:c.type}),this.hc[a]=c.str;else{let d=await this.$e(c);d||(d=this.Ye(c));this.wa[a]=d}}async $e(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Ye(a){a=this.qf(a);return this.Ue(a.data,
a.Df)}qf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Df:a,data:d}}Ue(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const G=self.L,Aa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),H={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ba={dispatchUserScriptEvent:!0},Ca={dispatchRuntimeEvent:!0};function Da(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ea(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function I(b){b=URL.createObjectURL(b);try{return await Ea(b)}finally{URL.revokeObjectURL(b)}}function Fa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ga(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await I(b);var d=await Fa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await I(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await I(b)}
function Ha(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ia=new Set(["input","textarea","datalist","select"]),Ja=new Set(["canvas","body","html"]);function J(b){b.target.tagName&&Ja.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ka(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function La(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await I(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ga(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ma=!1;document.addEventListener("pause",()=>Ma=!0);document.addEventListener("resume",()=>Ma=!1);function ua(b){b.addEventListener("selectstart",J);b.addEventListener("gesturehold",J);b.addEventListener("pointerdown",J)}function va(b){b.addEventListener("selectstart",Ka);b.addEventListener("gesturehold",Ka);b.addEventListener("touchstart",Ka)}function wa(b){b.Xd=!0;b.kd=b.j.ta();b.Eb=b.j.ja()}
function F(b){if(!b.na){var a=G.qb();a&&"any"!==b.td&&Na(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.ta(),innerHeight:b.ja()})}}async function Oa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Pa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Qa(b){return await self.C3_GetSvgImageSize(b.blob)}function Ra(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Sa(b){self.setTimeout(()=>{b.Wd=!0},1E3);"cordova"===b.j.u?(document.addEventListener("pause",()=>Ua(b,!0)),document.addEventListener("resume",()=>Ua(b,!1))):document.addEventListener("visibilitychange",()=>Ua(b,"hidden"===document.visibilityState));b.lc=!("hidden"!==document.visibilityState&&!Ma);return{isSuspended:b.lc}}
function Va(b){b.Sd||(b.Sd=!0,window.addEventListener("deviceorientation",a=>{b.na||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},H)}),window.addEventListener("deviceorientationabsolute",a=>{b.na||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},H)}))}
function Wa(b){b.Rd||(b.Rd=!0,window.addEventListener("devicemotion",a=>{if(!b.na){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},H)}}))}async function Xa(b){await Da(b.url)}
function Ya(b,a){b.Zd=a.message;-1===b.Zc&&(b.Zc=setTimeout(()=>{b.Zc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Zd)},250))}function Za(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:G.qb(),innerWidth:b.ta(),innerHeight:b.ja()})}
function Ua(b,a){b.lc!==a&&((b.lc=a)?b.j.Ic():b.j.Uc(),m(b,"visibilitychange",{hidden:a}),!a&&b.j.rb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function $a(b,a,c){"Backspace"===c.key&&J(c);if(b.j.ra()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.na||(d=Aa.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},H))}
function K(b,a,c,d){b.na||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Fa,pageX:c.pageX,pageY:c.pageY+b.Fa,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function N(b,a,c){if(!b.na){var d=0;"mouse"===c.pointerType&&(d=b.md);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Fa,pageX:c.pageX,pageY:c.pageY+b.Fa,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},H);"mouse"===c.pointerType&&
(b.md=c.buttons)}}function ab(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Fa=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Fa=a))}}
function bb(b,a,c,d){const e=b.ta(),f=b.ja();b.jb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.qb()}):10>d&&cb(b,e,f,d+1)}function cb(b,a,c,d){-1!==b.jb&&clearTimeout(b.jb);b.jb=setTimeout(()=>bb(b,a,c,d),48)}
function Na(b){b=b.td;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function db(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
G.Y(class extends self.ga{constructor(b){super(b,"runtime");this.Xd=!1;this.jb=-1;this.td="any";this.lc=this.Rd=this.Sd=!1;this.rc=document.createElement("div");this.rc.className="c3-screen-reader-text";this.rc.setAttribute("aria-live","polite");document.body.appendChild(this.rc);this.Na=null;this.na=!1;this.Zd="";this.Zc=-1;this.Wd=!1;this.kd=b.ta();this.Eb=b.ja();this.Fa=this.Nb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Oa(c));b.B("runtime","raster-svg-image",c=>Pa(c));b.B("runtime","get-svg-image-size",c=>Qa(c));b.B("runtime","set-target-orientation",c=>{this.td=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Ra(c));b.B("runtime","go-to-script",c=>Ra(c));b.B("runtime","before-start-ticking",()=>Sa(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Na||(this.Na=document.createElement("div"),this.Na.id="inspectOutline",document.body.appendChild(this.Na));var d=this.Na;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Na&&(this.Na.style.display="none")});b.B("runtime","enable-device-orientation",()=>Va(this));b.B("runtime","enable-device-motion",()=>Wa(this));b.B("runtime","add-stylesheet",c=>Xa(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Oc(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.rc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.na=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.j.Fd().style.display="";this.j.Se(c.duration)});b.B("runtime","export-to-video-progress",c=>Ya(this,c));b.B("runtime","exported-to-video",c=>{window.zf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.zf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ha(d)||c.preventDefault()});window.addEventListener("selectstart",J);window.addEventListener("gesturehold",J);window.addEventListener("touchstart",J,{passive:!1});window.addEventListener("pointerdown",J,{passive:!1});this.md=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",La,{passive:!1});window.addEventListener("wheel",La,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.na&&this.Xd){var c=this.ta();var d=this.ja();if(this.j.Gd()){if(this.Wd){if(this.kd===
c&&d<this.Eb){this.Nb=this.Eb-d;ab(this,this.Eb,this.Nb);c=void 0;break a}0<this.Nb&&(this.Nb=0,ab(this,d,this.Nb))}this.kd=c;this.Eb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.qb()});this.j.rb()&&(-1!==this.jb&&clearTimeout(this.jb),bb(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>F(this));window.addEventListener("webkitfullscreenchange",()=>F(this));window.addEventListener("mozfullscreenchange",()=>
F(this));window.addEventListener("fullscreenerror",c=>Za(this,c));window.addEventListener("webkitfullscreenerror",c=>Za(this,c));window.addEventListener("mozfullscreenerror",c=>Za(this,c));if(b.rb()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Ha(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.cb=new Set;this.jc=new WeakSet;this.Ba=!1}Ad(){window.addEventListener("focus",()=>{m(this,"window-focus",null,Ca)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},Ca);this.md=0});window.addEventListener("focusin",a=>{a=a.target;(Ia.has(a.tagName.toLowerCase())||Ha(a))&&m(this,"keyboard-blur",null,Ca)});window.addEventListener("keydown",a=>$a(this,"keydown",a));window.addEventListener("keyup",a=>$a(this,"keyup",a));window.addEventListener("mousedown",a=>K(this,"mousedown",a,Ba));window.addEventListener("mousemove",a=>K(this,"mousemove",a,Ba));window.addEventListener("mouseup",a=>K(this,"mouseup",a,Ba));window.addEventListener("dblclick",
a=>K(this,"dblclick",a,H));window.addEventListener("wheel",a=>{this.na||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Fa,pageX:a.pageX,pageY:a.pageY+this.Fa,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},H)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();db(a.target)&&document.activeElement&&!db(document.activeElement)&&document.activeElement.blur();N(this,"pointerdown",a)});this.j.fa&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a));window.addEventListener("pointerup",a=>N(this,"pointerup",a));window.addEventListener("pointercancel",a=>N(this,"pointercancel",a));const b=()=>this.Tc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.j.Ne()&&!this.j.Gd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{ab(this,this.ja(),navigator.virtualKeyboard.boundingRect.height)}));this.j.rb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}ta(){return this.j.ta()}ja(){return this.j.ja()}Tc(){var b=[...this.cb];this.cb.clear();if(!this.Ba)for(const a of b)(b=a.play())&&b.catch(()=>{this.jc.has(a)||this.cb.add(a)})}Ja(b){if("function"!==
typeof b.play)throw Error("missing play function");this.jc.delete(b);let a;try{a=b.play()}catch(c){this.cb.add(b);return}a&&a.catch(()=>{this.jc.has(b)||this.cb.add(b)})}Va(b){this.cb.delete(b);this.jc.add(b)}Tb(b){this.Ba=!!b}Oc(b){alert(b.message)}});"use strict";
async function sa(b){if(b.tf)throw Error("already initialised");b.tf=!0;var a=b.Da.Lc(("playable-ad"===b.Da.u?b.Da.ib:"")+"dispatchworker.js");b.Yc=await b.Da.yc(a,b.vb,{name:"DispatchWorker"});a=new MessageChannel;b.dd=a.port1;b.Yc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.od=await za(b)}function ta(b){return[b.dd,b.od]}
async function za(b){const a=b.fe.length;var c=b.Da.Lc(("playable-ad"===b.Da.u?b.Da.ib:"")+"jobworker.js");c=await b.Da.yc(c,b.vb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Yc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.fe.push(c);return e.port1}
self.Qe=class{constructor(b){this.Da=b;this.vb=b.ca;this.vb="preview"===b.u?this.vb+"workers/":this.vb+b.ib;this.vf=Math.min(navigator.hardwareConcurrency||2,16);this.Yc=null;this.fe=[];this.od=this.dd=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.L({If:!0,Jf:"workermain.js",kb:["scripts/c3runtime.js"],vc:[],yd:"",Ff:"scripts/",wc:["box2d.wasm.js"],ue:"html5"}));"use strict";function O(b){b.stopPropagation()}
self.L.Y(class extends self.Ta{constructor(b){super(b,"button")}nb(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",O);d.addEventListener("pointermove",
O);d.addEventListener("pointerrawupdate",O);d.addEventListener("pointerup",O);d.addEventListener("mousedown",O);d.addEventListener("mouseup",O);d.addEventListener("keydown",O);d.addEventListener("keyup",O);d.addEventListener("contextmenu",e=>e.preventDefault());c.addEventListener("click",()=>A(this,"click",b,{isChecked:c.checked}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.sa(d,a);return d}Kc(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}sa(b,a){const c="input"===b.tagName.toLowerCase()?
b:b.firstChild;c.checked=a.isChecked;c.disabled=!a.isEnabled;b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});"use strict";let eb=!1;async function fb(b){var a=gb(b.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:b.duration,startDelay:0,weakMagnitude:b.weakMag,strongMagnitude:b.strongMag})}catch(c){console.warn("[Gamepad] Failed to vibrate gamepad: ",c)}}
function hb(){try{return Array.from(navigator.getGamepads()).filter(b=>b&&b.connected)}catch(b){return eb||(console.warn("[Construct] Failed to access gamepads: ",b),eb=!0),[]}}function gb(b){for(const a of hb())if(a.index===b)return a;return null}
self.L.Y(class extends self.ga{constructor(b){super(b,"gamepad");this.ee=!!navigator.getGamepads;this.gd=!1;p(this,"is-supported",()=>this.ee);p(this,"ready",()=>{this.gd=!0;for(const a of hb())m(this,"gamepad-connected",{index:a.index,id:a.id});this.ee&&w(this)});p(this,"vibrate",a=>fb(a));p(this,"reset-vibrate",a=>{(a=gb(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.gd&&(a=a.gamepad,m(this,"gamepad-connected",{index:a.index,id:a.id}))});
window.addEventListener("gamepaddisconnected",a=>{this.gd&&m(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of hb()){const c=a.vibrationActuator;c&&c.reset&&c.reset()}})}Ia(){var b=hb();b.length&&(b=b.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(c=>({pressed:c.pressed,value:c.value})),axes:a.axes})),m(this,"input-update",b))}});"use strict";
self.L.Y(class extends self.ga{constructor(b){super(b,"mouse");v(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.j.Fd().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";function ib(){}function jb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function kb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.L.Y(class extends self.ga{constructor(b){super(b,"browser");this.u="";v(this,[["get-initial-state",a=>this.Qc(a)],["ready-for-sw-messages",()=>jb(this)],["alert",a=>this.Oc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Sc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>kb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||this.j.ra()?window.open(c,"_blank"):this.Of||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.j.ra()||"macos-wkwebview"===this.u)self.L.Yb(!0),this.j.Ka({type:"set-fullscreen",
fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(ib)}}],["exit-fullscreen",
()=>{if(this.j.ra()||"macos-wkwebview"===this.u)self.L.Yb(!1),this.j.Ka({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(ib)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;
a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",
e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}Qc(b){this.u=b.exportType;
return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}Oc(b){alert(b.message)}Sc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
"use strict";async function lb(b,a){a=a.type;let c=!0;0===a?c=await nb():1===a&&(c=await ob());m(b,"permission-result",{type:a,result:c})}async function nb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function ob(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.L.Y(class extends self.ga{constructor(b){super(b,"touch");p(this,"request-permission",a=>lb(this,a))}});"use strict";function P(b){b.stopPropagation()}function pb(b){const a=document.createElement("option");a.text=b;return a}
function qb(b){const a=b.selectedIndex,c=[];for(let d=0,e=b.length;d<e;++d)b.options[d].selected&&c.push(d);return{selectedIndex:a,selectedIndices:c}}
self.L.Y(class extends self.Ta{constructor(b){super(b,"list");y(this,"set-selected-index",(a,c)=>{a.selectedIndex=c.selectedIndex});y(this,"add-item",(a,c)=>{const d=c.index;c=pb(c.text);0>d?a.add(c):a.add(c,d)});y(this,"remove-item",(a,c)=>{a.remove(c.index)});y(this,"set-item",(a,c)=>{a.options[c.index].text=c.text});y(this,"clear",a=>{a.innerHTML=""});y(this,"load-state",(a,c)=>this.Rc(a,c))}nb(b,a){const c=a.isDropdown,d=a.isMultiSelect,e=a.items,f=document.createElement("select");f.style.position=
"absolute";f.style.userSelect="none";f.style.webkitUserSelect="none";f.multiple=d;c||(f.size=2);for(const g of e)f.add(pb(g));f.addEventListener("pointerdown",P);f.addEventListener("pointermove",P);f.addEventListener("pointerrawupdate",P);f.addEventListener("pointerup",P);f.addEventListener("mousedown",P);f.addEventListener("mouseup",P);f.addEventListener("click",g=>{g.stopPropagation();A(this,"click",b,qb(f))});f.addEventListener("dblclick",g=>{g.stopPropagation();A(this,"dblclick",b,qb(f))});f.addEventListener("change",
()=>x(this,"change",b,qb(f)));a.id&&(f.id=a.id);a.className&&(f.className=a.className);this.sa(f,a);return f}sa(b,a){b.title=a.title;b.disabled=!a.isEnabled;b.multiple=!!a.isMultiSelect}Rc(b,a){b.innerHTML="";for(const c of a.items)b.add(pb(c));b.selectedIndex=a.selectedIndex;for(const c of a.selectedIndices)if(a=b.options[c])a.selected=!0}});"use strict";
async function rb(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(b){return console.error("[Construct] Error requesting persistent storage: ",b),{isOk:!1}}}self.L.Y(class extends self.ga{constructor(b){super(b,"localstorage");v(this,[["init",()=>this.Ub()],["request-persistent",()=>rb()]])}async Ub(){let b=!1;try{b=await navigator.storage.persisted()}catch(a){b=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:b}}});"use strict";
function sb(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}function tb(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}function ub(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function vb(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}
async function wb(b){if(!b.Qa)try{b.Qa=await navigator.wakeLock.request("screen"),b.Qa.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Qa=null;m(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),m(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),m(b,"wake-lock-error")}}
async function xb(b){const a=await yb();m(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function yb(){var b=self.AndroidNotch;if(b)try{return await Promise.all([sb(b),tb(b),ub(b),vb(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.L.Y(class extends self.ga{constructor(b){super(b,"platform-info");v(this,[["get-initial-state",()=>this.Qc()],["request-wake-lock",()=>wb(this)],["release-wake-lock",()=>{this.Qa&&(this.Qa.release(),this.Qa=null)}]]);window.addEventListener("resize",()=>xb(this));this.Qa=null}async Qc(){const b=await yb();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==
typeof nw}}});"use strict";function Q(b){b.stopPropagation()}function zb(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.L.Y(class extends self.Ta{constructor(b){super(b,"text-input");y(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}nb(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",Q);c.addEventListener("pointermove",Q);c.addEventListener("pointerrawupdate",Q);c.addEventListener("pointerup",Q);c.addEventListener("mousedown",
Q);c.addEventListener("mouseup",Q);c.addEventListener("keydown",zb);c.addEventListener("keyup",zb);c.addEventListener("click",e=>{e.stopPropagation();A(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();A(this,"dblclick",b)});c.addEventListener("input",()=>x(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.sa(c,a);return c}sa(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;
b.spellcheck=a.spellCheck;a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});"use strict";function R(b){b.stopPropagation()}
self.L.Y(class extends self.Ta{constructor(b){super(b,"sliderbar")}nb(b,a){const c=document.createElement("input");c.type="range";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",R);c.addEventListener("pointermove",R);c.addEventListener("pointerrawupdate",R);c.addEventListener("pointerup",R);c.addEventListener("mousedown",R);c.addEventListener("mouseup",R);c.addEventListener("keydown",R);c.addEventListener("keyup",R);c.addEventListener("contextmenu",
d=>d.preventDefault());c.addEventListener("click",()=>A(this,"click",b));c.addEventListener("change",()=>x(this,"change",b,{value:parseFloat(c.value)}));c.addEventListener("input",()=>x(this,"input",b,{value:parseFloat(c.value)}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.sa(c,a);return c}sa(b,a){b.max=a.max;b.min=a.min;b.step=a.step;b.value=a.value;b.disabled=!a.isEnabled;b.title=a.title}});"use strict";const Ab=180/Math.PI;
async function Bb(b,a){if(a.isiOSCordova||a.isSafari)b.nc=!0;b.ud=a.timeScaleMode;b.ke=["equalpower","HRTF","soundfield"][a.panningModel];b.Vd=["linear","inverse","exponential"][a.distanceModel];b.le=a.refDistance;b.je=a.maxDistance;b.ne=a.rolloffFactor;if(b.j.ed)b.nc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.j.Yd)});else{var c={latencyHint:a.latencyHint};b.qe||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");Cb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&Cb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Za=b.g.createGain();b.Za.connect(b.g.destination);c=a.listenerPos;b.ba[0]=c[0];b.ba[1]=c[1];b.ba[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.da);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
Db(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function Eb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,q=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.ge=g.slice(0);Fb(b,g);try{b.S=await Gb(b,c,d,e,g,f);if(q){S(b.S,!0);var u=b.S,E=q.innerAngle,xa=q.outerAngle,ya=q.outerGain;if(u.Cb){Hb(u,q.x,q.y,q.z,q.angle);var M=self.mb.Te;u.xa[0]!==M(E)&&
(u.xa[0]=M(E),u.F.coneInnerAngle=M(E));u.xa[1]!==M(xa)&&(u.xa[1]=M(xa),u.F.coneOuterAngle=M(xa));u.xa[2]!==ya&&(u.xa[2]=ya,u.F.coneOuterGain=ya)}q.hasOwnProperty("uid")&&(b.S.va=q.uid)}else"number"===typeof r&&0!==r?(T(b.S,!0),Ib(b.S,r)):(S(b.S,!1),T(b.S,!1));b.S.Play(h,k,l,t)}catch(Yb){console.error("[Construct] Audio: error starting playback: ",Yb);return}finally{c=g.join(" ");d=b.Kb.get(c);if(!d)throw Error("expected pending tag");d.zd--;0===d.zd&&(d.resolve(),b.Kb.delete(c))}w(b)}
async function Jb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await Kb(b,c);for(const h of U(b,c))if(!h.Aa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Sa=d;h.ab=g;h.pe=a}Lb(b)}async function Mb(b,a){const c=a.tags;a=a.rate;await Kb(b,c);for(const d of U(b,c))d.oa!==a&&(d.oa=a,d.La())}async function Nb(b,a){const c=a.tags;a=a.pos;await Kb(b,c);for(const d of U(b,c))d.Ec(a)}
async function Ob(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await Gb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function Pb(b,a){if(a=await Db(b,"",a.url,a.type,a.isMusic,!0))a.l(),a=b.la.indexOf(a),-1!==a&&b.la.splice(a,1)}
async function Qb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await Db(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.Ae(b,...e);else if("delay"===c)d=new self.ye(b,...e);else if("convolution"===c){var g=d=new self.xe(b,f.ka,...e),h=a.bufferType;g.Td=a.bufferOriginalUrl;g.Ud=h}else if("flanger"===c)d=
new self.Be(b,...e);else if("phaser"===c)d=new self.De(b,...e);else if("gain"===c)d=new self.Ce(b,...e);else if("stereopan"===c)d=new self.Fe(b,...e);else if("tremolo"===c)d=new self.Ge(b,...e);else if("ringmod"===c)d=new self.Ee(b,...e);else if("distortion"===c)d=new self.ze(b,...e);else if("compressor"===c)d=new self.we(b,...e);else if("analyser"===c)d=new self.ve(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ma.get(h);l||(l=[],g.ma.set(h,l));d.ce=l.length;d.sd=
h;l.push(d);Rb(g,h)}Sb(b)}async function Tb(b,a){try{const c=b.g.suspend(a.time);b.be?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.j.tb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Ub(d)),b.be=!0);await c}catch(c){Ub(c)}}
function Cb(b){b.bc||(b.cd=!1,window.addEventListener("pointerup",b.Ea,!0),window.addEventListener("touchend",b.Ea,!0),window.addEventListener("click",b.Ea,!0),window.addEventListener("keydown",b.Ea,!0),b.bc=!0)}
async function Db(b,a,c,d,e,f){for(var g of b.la)if(g.pb()===c)return await Vb(g),g;if(f)return null;if(e&&(b.nc||b.ae)){f=0;for(let h=0,k=b.la.length;h<k;++h)g=b.la[h],b.la[f]=g,g.Ga()?g.l():++f;b.la.length=f}f="audio/webm; codecs=opus"===d&&!b.qe;e&&f&&(b.ae=!0);c=!e||b.nc||f?new self.Je(b,a,c,d,e,f):new self.He(b,a,c,d,e);b.la.push(c);await Vb(c);b.ie.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.ia()}),b.ie.add(a));return c}
function Wb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Xb(b,a){return(a=b.ma.get(a.toLowerCase()))?a[0].O():b.ha()}function Rb(b,a){a=a.toLowerCase();let c=b.ha();var d=b.ma.get(a);if(d&&d.length){c=d[0].O();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.V(b.ha()):e.V(d[f+1].O())}}for(const f of Zb(b,a))d=c,e=f.ea||f.F||f.G,e.disconnect(),e.connect(d);b.Pa&&b.ld===a&&(b.Pa.disconnect(),b.Pa.connect(c))}
function*Zb(b,a){if(a)for(const c of b.H)Wb(0<c.qa.length?c.qa[0]:"",a)&&(yield c);else b.S&&!b.S.P()&&(yield b.S)}function $b(b,a,c){return c?b.j.sf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function ac(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.R===a?f.l():++c}b.H.length=c}
function*U(b,a){if(0<a.length)for(const d of b.H){a:{b=d.qa;var c=a;for(const e of c){c=!1;for(const f of b)if(Wb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.S&&!b.S.P()&&(yield b.S)}async function Gb(b,a,c,d,e,f){for(const g of b.H)if(g.pb()===c&&(g.xc()||f))return g.qa=e,g;a=await Db(b,a,c,d,f);e="html5"===a.Wc?new self.Ie(a.v,a,e):new self.Ke(a.v,a,e);b.H.push(e);return e}
function Fb(b,a){a=a.join(" ");let c=b.Kb.get(a);if(!c){let d=null;c={zd:0,promise:new Promise(e=>d=e),resolve:d};b.Kb.set(a,c)}c.zd++}function Kb(b,a){return(b=b.Kb.get((0===a.length?b.ge:a).join(" ")))?b.promise:Promise.resolve()}function Lb(b){if(0<b.Xa.size)w(b);else for(const a of b.H)if(!a.I&&!a.P()){w(b);break}}function bc(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function Sb(b){b.fd||(b.fd=!0,Promise.resolve().then(()=>cc(b)))}
function cc(b){const a={};for(const [c,d]of b.ma)a[c]=d.map(e=>e.ob());m(b,"fxstate",{fxstate:a});b.fd=!1}
async function dc(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await Gb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(S(b,!0),e=b.F,f=d.pos,b.fb[0]=f[0],b.fb[1]=f[1],b.fb[2]=f[2],f=d.orient,b.eb[0]=f[0],b.eb[1]=f[1],b.eb[2]=f[2],e.setPosition(...b.fb),e.setOrientation(...b.eb),b.xa[0]=d.cia,b.xa[1]=d.coa,b.xa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.va=d.uid):S(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?T(b,!1):(T(b,!0),Ib(b,d));c.Play(k,l,q,0);a.isPlaying||c.sb();c.Nc(a)}}}function Ub(b){console.error("[Audio] Offline rendering error: ",b)}
self.mb=class extends self.ga{constructor(b){super(b,"audio");this.Za=this.g=null;this.bc=this.cd=!1;this.Ea=()=>{if(!this.cd){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.bc&&(this.cd=!0,window.removeEventListener("pointerup",this.Ea,!0),window.removeEventListener("touchend",this.Ea,!0),window.removeEventListener("click",this.Ea,!0),window.removeEventListener("keydown",
this.Ea,!0),this.bc=!1)}};this.la=[];this.H=[];this.S=null;this.ge=[];this.ie=new Set;this.he=-1;this.Kb=new Map;this.ic=1;this.Ba=!1;this.ud=0;this.sc=1;this.$c=0;this.ke="HRTF";this.Vd="inverse";this.le=600;this.je=1E4;this.ne=1;this.ba=[0,0,0];this.da=[0,0,-1,0,1,0];this.ae=this.nc=!1;this.qe=this.j.Oe();this.ma=new Map;this.Xa=new Set;this.be=this.fd=!1;this.ld="";this.Pa=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Pa&&this.Pa.disconnect();this.ld=c.toLowerCase();this.Pa=this.g.createMediaStreamSource(a);
this.Pa.connect(Xb(this,this.ld))};this.ac=null;self.C3Audio_GetOutputStream=()=>{this.ac||(this.ac=this.g.createMediaStreamDestination(),this.Za.connect(this.ac));return this.ac.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>Bb(this,a)],["play",a=>Eb(this,a)],["stop",a=>{a=a.tags;for(const c of U(this,a))c.Ha()}],["stop-all",()=>{for(const a of this.H)a.Ha()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of U(this,c))a?d.sb():d.Sb();Lb(this)}],["set-volume",
a=>{const c=a.tags;a=a.vol;for(const d of U(this,c))V(d,a)}],["fade-volume",a=>Jb(this,a)],["set-master-volume",a=>{this.ic=a.vol;this.Za.gain.value=this.ic}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of U(this,c))ec(d,a)}],["set-silent",a=>{this.Ba=a.isSilent;this.j.Tb(this.Ba);for(const c of this.H)c.Zb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of U(this,c))d.Fc(a)}],["set-playback-rate",a=>Mb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of U(this,
c))T(d,!0),Ib(d,a)}],["seek",a=>Nb(this,a)],["preload",a=>Ob(this,a)],["unload",a=>Pb(this,a)],["unload-all",()=>{for(const a of this.la)a.l();this.la.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Gc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Qb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ma.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].aa(e,
f,g,a);Sb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ma.get(a);if(!d||!d.length)break;for(const e of d)e.l();this.ma.delete(a);Rb(this,a)}}],["tick",a=>{this.sc=a.timeScale;this.$c=a.gameTime;this.he=a.tickCount;if(0!==this.ud)for(var c of this.H)c.La();!(c=a.listenerPos)||this.ba[0]===c[0]&&this.ba[1]===c[1]&&this.ba[2]===c[2]||(this.ba[0]=c[0],this.ba[1]=c[1],this.ba[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.da[0]!==
c[0]||this.da[1]!==c[1]||this.da[2]!==c[2]||this.da[3]!==c[3]||this.da[4]!==c[4]||this.da[5]!==c[5])){for(let d=0;6>d;++d)this.da[d]=c[d];this.g.listener.setOrientation(...this.da)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.va===a&&Hb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>this.Rc(a)],["offline-render-audio",a=>Tb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}W(){return this.g}ha(){return this.Za}GetAudioContextExtern(){return this.W()}GetDestinationNodeExtern(){return this.ha()}Rb(){return this.Ba}Ja(b){this.j.Ja(b)}Va(b){this.j.Va(b)}Ia(){for(var b of this.Xa)b.Ia();
b=this.g.currentTime;for(var a of this.H)a.Ia(b);a=this.H.filter(c=>!c.I&&!c.P()).map(c=>c.ob());m(this,"state",{tickCount:this.he,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Xa].map(c=>({tag:c.sd,index:c.ce,peak:c.gb,rms:c.me,binCount:c.m.frequencyBinCount,freqBins:c.$d}))});0===a.length&&0===this.Xa.size&&this.cc&&(this.j.Pd(this.re),this.cc=!1)}async Rc(b){const a=b.saveLoadMode;if(3!==a){var c=[];for(var d of this.H)d.Ga()&&1===a||!d.Ga()&&2===a?c.push(d):d.l();this.H=
c}for(const e of this.ma.values())for(const f of e)f.l();this.ma.clear();this.sc=b.timeScale;this.$c=b.gameTime;c=b.listenerPos;this.ba[0]=c[0];this.ba[1]=c[1];this.ba[2]=c[2];this.g.listener.setPosition(c[0],c[1],c[2]);c=b.listenerOrientation;if(Array.isArray(c)){for(d=0;6>d;++d)this.da[d]=c[d];this.g.listener.setOrientation(...this.da)}this.Ba=b.isSilent;this.j.Tb(this.Ba);this.ic=b.masterVolume;this.Za.gain.value=this.ic;c=[];for(const e of Object.values(b.effects))c.push(Promise.all(e.map(f=>
Qb(this,f))));await Promise.all(c);await Promise.all(b.playing.map(e=>dc(this,e,a)));Lb(this)}static Te(b){return b*Ab}static Ed(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Re(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.L.Y(self.mb);"use strict";function Vb(b){b.fc||(b.fc=b.Mc());return b.fc}self.Bd=class{constructor(b,a,c,d,e){this.v=b;this.xf=a;this.Ra=c;this.U=d;this.uf=e;this.Wc="";this.fc=null}l(){this.fc=this.v=null}Mc(){}W(){return this.v.W()}Bc(){return this.xf}pb(){return this.Ra}Ac(){return this.U}Ga(){return this.uf}ia(){}};
"use strict";
self.He=class extends self.Bd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Wc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.Fb=this.Gb=null;this.M.addEventListener("canplaythrough",()=>!0);this.Jb=this.W().createGain();this.Ib=null;this.M.addEventListener("canplay",()=>{this.Gb&&(this.Gb(),this.Fb=this.Gb=null);!this.Ib&&this.M&&(this.Ib=this.W().createMediaElementSource(this.M),this.Ib.connect(this.Jb))});this.onended=null;this.M.addEventListener("ended",()=>
{if(this.onended)this.onended()});this.M.addEventListener("error",f=>this.Vb(f))}l(){ac(this.v,this);this.Jb.disconnect();this.Jb=null;this.Ib.disconnect();this.Ib=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.l()}Mc(){return new Promise((b,a)=>{this.Gb=b;this.Fb=a;this.M.src=this.Ra})}Vb(b){console.error(`[Construct] Audio '${this.Ra}' error: `,b);this.Fb&&(this.Fb(b),this.Fb=this.Gb=null)}X(){return this.M}ia(){return this.M.duration}};"use strict";
async function fc(b){if(b.Ma)return b.Ma;var a=b.v.j;if("cordova"===a.u&&a.Hd(b.Ra)&&a.dc)b.Ma=await a.Pb(b.Ra);else{a=await fetch(b.Ra);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ma=await a.arrayBuffer()}}async function gc(b){if(b.ka)return b.ka;b.ka=await $b(b.v,b.Ma,b.wf);b.Ma=null}
self.Je=class extends self.Bd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Wc="webaudio";this.ka=this.Ma=null;this.wf=!!f}l(){ac(this.v,this);this.ka=this.Ma=null;super.l()}async Mc(){try{await fc(this),await gc(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ra}': `,b)}}ia(){return this.ka?this.ka.duration:0}};"use strict";let hc=0;
function S(b,a){a=!!a;b.Cb!==a&&(b.Cb=a,b.Cb?(T(b,!1),b.F||(b.F=b.W().createPanner(),b.F.panningModel=b.v.ke,b.F.distanceModel=b.v.Vd,b.F.refDistance=b.v.le,b.F.maxDistance=b.v.je,b.F.rolloffFactor=b.v.ne),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ha())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ha())))}
function T(b,a){a=!!a;b.ec!==a&&(b.ec=a,b.ec?(S(b,!1),b.ea=b.W().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ea),b.ea.connect(b.ha())):(b.ea.disconnect(),b.ea=null,b.G.disconnect(),b.G.connect(b.ha())))}function Ib(b,a){b.ec&&b.rd!==a&&(b.ea.pan.value=a,b.rd=a)}function V(b,a){b.Sa=a;b.G.gain.cancelScheduledValues(0);b.ab=-1;b.G.gain.value=b.Cc()}function ec(b,a){a=!!a;b.Aa!==a&&(b.Aa=a,b.Zb())}
function Hb(b,a,c,d,e){if(b.Cb){var f=b.fb,g=b.eb,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function ic(b){return b.hd?b.v.$c:performance.now()/1E3}
self.Cd=class{constructor(b,a,c){this.v=b;this.R=a;this.qa=c;this.$b=hc++;this.G=this.W().createGain();this.G.connect(this.ha());this.F=null;this.Cb=!1;this.fb=[0,0,0];this.eb=[0,0,0];this.xa=[0,0,0];this.ea=null;this.ec=!1;this.rd=0;this.I=!0;this.$=this.ya=this.J=!1;this.Sa=1;this.Aa=!1;this.oa=1;b=this.v.ud;this.hd=1===b&&!this.Ga()||2===b;this.ab=this.va=-1;this.pe=!1}l(){this.R=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.ea&&(this.ea.disconnect(),this.ea=null);this.G.disconnect();
this.G=null}W(){return this.v.W()}ha(){return Xb(this.v,0<this.qa.length?this.qa[0]:"")}Bc(){return this.R.Bc()}pb(){return this.R.pb()}Ac(){return this.R.Ac()}Ga(){return this.R.Ga()}P(){}xc(){}IsPlaying(){return!this.I&&!this.J&&!this.P()}Ua(){}ia(){return this.R.ia()}Play(){}Ha(){}sb(){}Sb(){}Ia(b){-1!==this.ab&&b>=this.ab&&(this.ab=-1,this.pe&&this.Ha(),bc(this.v,"fade-ended",this.qa,this.$b))}Cc(){const b=this.Sa;return isFinite(b)?b:0}Rb(){return this.v.Rb()}Zb(){}Fc(){}La(){}Ec(){}Gc(){}Dc(){}ob(){var b=
this.$b,a=this.qa,c=this.ia(),d=-1===this.ab?this.Sa:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.fb,orient:this.eb,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.va}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ua(),playbackRate:this.oa,uid:this.va,bufferOriginalUrl:this.Bc(),bufferUrl:"",bufferType:this.Ac(),isMusic:this.Ga(),isLooping:this.$,isMuted:this.Aa,resumePosition:this.Dc(),pan:f,stereoPan:this.ea?
this.rd:null}}Nc(b){var a=b.playbackRate;this.oa!==a&&(this.oa=a,this.La());ec(this,b.isMuted)}};"use strict";
self.Ie=class extends self.Cd{constructor(b,a,c){super(b,a,c);this.R.Jb.connect(this.G);this.R.onended=()=>this.Pc()}l(){this.Ha();this.R.Jb.disconnect();super.l()}X(){return this.R.X()}Pc(){this.I=!0;this.va=-1;bc(this.v,"ended",this.qa,this.$b)}P(){return this.X().ended}xc(){return this.I?!0:this.P()}Ua(){let b=this.X().currentTime;this.$||(b=Math.min(b,this.ia()));return b}Play(b,a,c){const d=this.X();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);V(this,a);this.Aa=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.R.pb()}' to position '${c}': `,e)}this.v.Ja(d);this.J=this.I=!1;this.$=b;this.oa=1}Ha(){const b=this.X();b.paused||b.pause();this.v.Va(b);this.I=!0;this.J=!1;this.va=-1}sb(){if(!(this.J||this.I||this.P())){var b=this.X();b.paused||b.pause();this.v.Va(b);this.J=!0}}Sb(){!this.J||this.I||this.P()||(this.v.Ja(this.X()),this.J=!1)}Zb(){this.X().muted=this.Aa||this.Rb()}Fc(b){b=!!b;this.$!==
b&&(this.$=b,this.X().loop=b)}La(){let b=this.oa;this.hd&&(b*=this.v.sc);try{this.X().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}Ec(b){if(!this.I&&!this.P())try{this.X().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}Dc(){return this.Ua()}Gc(b){b?this.IsPlaying()?(this.X().pause(),this.ya=!0):this.ya=!1:this.ya&&(this.v.Ja(this.X()),this.ya=!1)}};"use strict";
function W(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.ub=null}
self.Ke=class extends self.Cd{constructor(b,a,c){super(b,a,c);this.s=null;this.kc=d=>this.Pc(d);this.bd=!0;this.ub=null;this.T=this.mc=this.oc=0;this.nd=1}l(){this.Ha();W(this);this.kc=null;super.l()}Pc(b){this.J||this.ya||b.target!==this.ub||(this.I=this.bd=!0,this.va=-1,W(this),bc(this.v,"ended",this.qa,this.$b))}P(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.bd}xc(){return!this.s||this.I?!0:this.P()}Ua(){let b;b=this.J?this.T:this.mc+(ic(this)-this.oc)*this.oa;this.$||(b=Math.min(b,this.ia()));
return b}Play(b,a,c,d){this.Aa=!1;this.nd=1;V(this,a);W(this);this.s=this.W().createBufferSource();this.s.buffer=this.R.ka;this.s.connect(this.G);this.ub=this.s;this.s.onended=this.kc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.bd=!1;this.$=b;this.oa=1;this.oc=ic(this);this.mc=c}Ha(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.va=-1}sb(){this.J||this.I||this.P()||(this.T=this.Ua(),this.$&&(this.T%=this.ia()),this.J=!0,this.s.stop(0))}Sb(){!this.J||this.I||this.P()||(W(this),
this.s=this.W().createBufferSource(),this.s.buffer=this.R.ka,this.s.connect(this.G),this.ub=this.s,this.s.onended=this.kc,this.s.loop=this.$,V(this,this.Sa),this.La(),this.s.start(0,this.T),this.oc=ic(this),this.mc=this.T,this.J=!1)}Cc(){return super.Cc()*this.nd}Zb(){this.nd=this.Aa||this.Rb()?0:1;V(this,this.Sa)}Fc(b){b=!!b;this.$!==b&&(this.$=b,this.s&&(this.s.loop=b))}La(){let b=this.oa;this.hd&&(b*=this.v.sc);this.s&&(this.s.playbackRate.value=b)}Ec(b){this.I||this.P()||(this.J?this.T=b:(this.sb(),
this.T=b,this.Sb()))}Dc(){return this.T}Gc(b){b?this.IsPlaying()?(this.ya=!0,this.T=this.Ua(),this.$&&(this.T%=this.ia()),this.s.stop(0)):this.ya=!1:this.ya&&(W(this),this.s=this.W().createBufferSource(),this.s.buffer=this.R.ka,this.s.connect(this.G),this.ub=this.s,this.s.onended=this.kc,this.s.loop=this.$,V(this,this.Sa),this.La(),this.s.start(0,this.T),this.oc=ic(this),this.mc=this.T,this.ya=!1)}Nc(b){super.Nc(b);this.T=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.v=b;this.g=b.W();this.ce=-1;this.U=this.sd="";this.o=null}l(){this.g=null}O(){}V(){}ob(){return{type:this.U,tag:this.sd,params:this.o}}}
self.Ae=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.U="filter";this.o=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}l(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.l()}V(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}O(){return this.A}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.ye=class extends Z{constructor(b,a,c,d){super(b);this.U="delay";this.o=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.Hb=X(this);this.Z=this.g.createDelay(a);this.Z.delayTime.value=a;this.yb=X(this);this.yb.gain.value=c;this.A.connect(this.Hb);this.A.connect(this.h);this.Hb.connect(this.i);this.Hb.connect(this.Z);this.Z.connect(this.yb);this.yb.connect(this.Hb)}l(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.Hb.disconnect();
this.Z.disconnect();this.yb.disconnect();super.l()}V(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}O(){return this.A}aa(b,a,c,d){const e=self.mb.Ed;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);Y(this,this.yb.gain,e(a),c,d);break;case 5:this.o[0]=a,Y(this,this.Z.delayTime,a,c,d)}}};
self.xe=class extends Z{constructor(b,a,c,d){super(b);this.U="convolution";this.o=[c,d];this.Ud=this.Td="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.xb=this.g.createConvolver();this.xb.normalize=c;this.xb.buffer=a;this.A.connect(this.xb);this.A.connect(this.h);this.xb.connect(this.i)}l(){this.A.disconnect();this.xb.disconnect();this.i.disconnect();this.h.disconnect();super.l()}V(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}O(){return this.A}aa(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}ob(){const b=super.ob();b.bufferOriginalUrl=this.Td;b.bufferUrl="";b.bufferType=this.Ud;return b}};
self.Be=class extends Z{constructor(b,a,c,d,e,f){super(b);this.U="flanger";this.o=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.Ab=X(this);this.Ab.gain.value=e;this.Z=this.g.createDelay(a+c);this.Z.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.A.connect(this.Z);this.A.connect(this.h);this.Z.connect(this.i);this.Z.connect(this.Ab);this.Ab.connect(this.Z);this.C.connect(this.K);
this.K.connect(this.Z.delayTime);this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.Z.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.Ab.disconnect();super.l()}V(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}O(){return this.A}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,Y(this,this.Ab.gain,a/100,c,d)}}};
self.De=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.U="phaser";this.o=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.l()}V(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}O(){return this.A}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;Y(this,this.D.detune,a,c,
d);break;case 3:this.o[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.Ce=class extends Z{constructor(b,a){super(b);this.U="gain";this.o=[a];this.m=X(this);this.m.gain.value=a}l(){this.m.disconnect();super.l()}V(b){this.m.disconnect();this.m.connect(b)}O(){return this.m}aa(b,a,c,d){const e=self.mb.Ed;switch(b){case 4:this.o[0]=e(a),Y(this,this.m.gain,e(a),c,d)}}};
self.Fe=class extends Z{constructor(b,a){super(b);this.U="stereopan";this.o=[a];this.m=this.g.createStereoPanner();this.m.pan.value=a}l(){this.m.disconnect();super.l()}V(b){this.m.disconnect();this.m.connect(b)}O(){return this.m}aa(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,Y(this,this.m.pan,a,c,d)}}};
self.Ge=class extends Z{constructor(b,a,c){super(b);this.U="tremolo";this.o=[a,c];this.m=X(this);this.m.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.m.gain);this.C.start(0)}l(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.m.disconnect();super.l()}V(b){this.m.disconnect();this.m.connect(b)}O(){return this.m}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;Y(this,this.m.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.Ee=class extends Z{constructor(b,a,c){super(b);this.U="ringmod";this.o=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Mb=X(this);this.Mb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Mb.gain);this.C.start(0);this.A.connect(this.Mb);this.A.connect(this.h);this.Mb.connect(this.i)}l(){this.C.stop(0);this.C.disconnect();this.Mb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.l()}V(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}O(){return this.A}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.ze=class extends Z{constructor(b,a,c,d,e,f){super(b);this.U="distortion";this.o=[a,c,d,e,f];this.A=X(this);this.qc=X(this);this.pc=X(this);b=d;.01>b&&(b=.01);this.qc.gain.value=b;this.pc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.uc=this.g.createWaveShaper();this.Xc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Xc[32768+e]=f,this.Xc[32768-
e-1]=-f;this.uc.curve=this.Xc;this.A.connect(this.qc);this.A.connect(this.h);this.qc.connect(this.uc);this.uc.connect(this.pc);this.pc.connect(this.i)}l(){this.A.disconnect();this.qc.disconnect();this.uc.disconnect();this.pc.disconnect();this.i.disconnect();this.h.disconnect();super.l()}V(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}O(){return this.A}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.we=class extends Z{constructor(b,a,c,d,e,f){super(b);this.U="compressor";this.o=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}l(){this.m.disconnect();super.l()}V(b){this.m.disconnect();this.m.connect(b)}O(){return this.m}aa(){}};
self.ve=class extends Z{constructor(b,a,c){super(b);this.U="analyser";this.o=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.$d=new Float32Array(this.m.frequencyBinCount);this.oe=new Uint8Array(a);this.me=this.gb=0;b=this.v;b.Xa.add(this);Lb(b)}l(){this.v.Xa.delete(this);this.m.disconnect();super.l()}Ia(){this.m.getFloatFrequencyData(this.$d);this.m.getByteTimeDomainData(this.oe);const b=this.m.fftSize;let a=this.gb=0;for(var c=0;c<b;++c){let d=(this.oe[c]-
128)/128;0>d&&(d=-d);this.gb<d&&(this.gb=d);a+=d*d}c=self.mb.Re;this.gb=c(this.gb);this.me=c(Math.sqrt(a/b))}V(b){this.m.disconnect();this.m.connect(b)}O(){return this.m}aa(){}};"use strict";function jc(b,a){navigator.geolocation.getCurrentPosition(c=>kc(b,c),c=>b.Vb(c),a)}function lc(b,a){mc(b);b.tc=navigator.geolocation.watchPosition(c=>kc(b,c),c=>b.Vb(c),a)}function mc(b){-1!==b.tc&&(navigator.geolocation.clearWatch(b.tc),b.tc=-1)}
function kc(b,a){const c=a.coords;m(b,"update",{timestamp:a.timestamp,coords:{latitude:c.latitude,longitude:c.longitude,altitude:c.altitude,accuracy:c.accuracy,altitudeAccuracy:c.altitudeAccuracy,heading:c.heading,speed:c.speed}})}self.L.Y(class extends self.ga{constructor(b){super(b,"geolocation");this.tc=-1;p(this,"request-location",a=>jc(this,a));p(this,"watch-location",a=>lc(this,a));p(this,"stop-watching",()=>mc(this))}Vb(b){m(this,"error",{message:b.message||"Unknown error"})}});
