function k(b,a,d,c){b.i.oa(b.R,a,d,c,void 0)}function p(b,a,d,c){b.i.v?k(b,a,d,c):b.i.yb()._OnMessageFromDOM({type:"event",component:b.R,handler:a,dispatchOpts:c||null,data:d,responseId:null})}function q(b,a,d){b.i.h(b.R,a,d)}function r(b,a){for(const [d,c]of a)q(b,d,c)}window.ba=class{constructor(b,a){this.i=b;this.R=a;this.$a=!1;this.Qb=()=>this.Ma()}Ia(){}Ma(){}};
window.ob=class{constructor(b){this.Va=b;this.Lb=5;this.K=-1;this.ga=-Infinity;this.Rb=()=>{this.K=-1;this.ga=Date.now();this.S=!0;this.Va();this.S=!1};this.Wa=this.S=!1}};"use strict";function aa(b,a){const d=a.elementId,c=b.Ka(d,a);b.s.set(d,c);c.style.boxSizing="border-box";a.isVisible||(c.style.display="none");a=b.ra(c);a.addEventListener("focus",()=>{t(b,"elem-focused",d)});a.addEventListener("blur",()=>{t(b,"elem-blurred",d)});b.ea&&document.body.appendChild(c)}
function ca(b,a){q(b,"get-element",d=>{const c=b.s.get(d.elementId);return a(c,d)})}function t(b,a,d){var c;c||(c={});c.elementId=d;k(b,a,c)}
window.hb=class extends self.ba{constructor(b){super(b,"button");this.s=new Map;this.ea=!0;r(this,[["create",a=>aa(this,a)],["destroy",a=>{a=a.elementId;const d=this.s.get(a);this.ea&&d.parentElement.removeChild(d);this.s.delete(a)}],["set-visible",a=>{this.ea&&(this.s.get(a.elementId).style.display=a.isVisible?"":"none")}],["update-position",a=>{if(this.ea){var d=this.s.get(a.elementId);d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=a.width+"px";d.style.height=a.height+"px";a=a.fontSize;
null!==a&&(d.style.fontSize=a+"em")}}],["update-state",a=>{const d=this.s.get(a.elementId);this.pa(d,a)}],["focus",a=>{const d=this.ra(this.s.get(a.elementId));a.focus?d.focus():d.blur()}],["set-css-style",a=>{const d=this.s.get(a.elementId),c=a.prop;a=a.val;c.startsWith("--")?d.style.setProperty(c,a):d.style[c]=a}],["set-attribute",a=>{this.s.get(a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{this.s.get(a.elementId).removeAttribute(a.name)}]]);ca(this,a=>a)}Ka(){throw Error("required override");
}pa(){throw Error("required override");}ra(b){return b}};"use strict";const u=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),v=/android/i.test(navigator.userAgent);let w=0;function x(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Wb?new Promise(d=>{const c="c3_resolve_"+w;++w;self[c]=d;a.textContent=b.$b+`\n\nself["${c}"]();`;document.head.appendChild(a)}):new Promise((d,c)=>{a.onload=d;a.onerror=c;a.src=b;document.head.appendChild(a)})}
let y=!1,z=!1;function da(){if(!y){try{new Worker("blob://",{get type(){z=!0}})}catch(b){}y=!0}return z}let A=new Audio;const ea={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;
async function fa(b){b=await ha(b);return(new TextDecoder("utf-8")).decode(b)}function ha(b){return new Promise((a,d)=>{const c=new FileReader;c.onload=e=>a(e.target.result);c.onerror=e=>d(e);c.readAsArrayBuffer(b)})}const B=[];let C=0;window.RealFile=window.File;const D=[],E=new Map,F=new Map;let ia=0;const ja=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ja.push(b)};const ka=new Set(["cordova","playable-ad","instant-games"]);
let la=!1;
window.O=class b{constructor(a){this.v=a.bc;this.V=null;this.m="";this.I=a.Zb;this.$={};this.Ba=this.L=null;this.fa=[];this.j=this.Y=null;this.ab=!1;this.T=null;this.H=-1;this.Pb=()=>this.Fb();this.Ea=[];this.g=a.fb;this.ya="file"===location.protocol.substr(0,4);!this.v||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&da()||(this.v=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.v=!1;if("cordova"===this.g&&this.v)if(v){const d=/Chrome\/(\d+)/i.exec(navigator.userAgent);d&&
90<=parseInt(d[1],10)||(this.v=!1)}else this.v=!1;this.ha=this.B=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime","cordova-fetch-local-file",d=>this.Bb(d));this.h("runtime","create-job-worker",()=>this.Cb());"cordova"===this.g?document.addEventListener("deviceready",()=>this.Pa(a)):this.Pa(a)}lb(){return u&&
"cordova"===this.g}na(){const a=navigator.userAgent;return u&&ka.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}jb(){return v}La(){return v&&ka.has(this.g)}async Pa(a){"macos-wkwebview"===this.g&&this.Jb();if("playable-ad"===this.g){this.B=self.c3_base64files;this.ha={};await this.ub();for(let c=0,e=a.M.length;c<e;++c){var d=a.M[c];this.ha.hasOwnProperty(d)?a.M[c]={Wb:!0,$b:this.ha[d]}:this.B.hasOwnProperty(d)&&(a.M[c]=URL.createObjectURL(this.B[d]))}}a.Yb?this.m=a.Yb:(d=location.origin,
this.m=("null"===d?"file:///":d)+location.pathname,d=this.m.lastIndexOf("/"),-1!==d&&(this.m=this.m.substr(0,d+1)));a.dc&&(this.$=a.dc);d=new MessageChannel;this.V=d.port1;this.V.onmessage=c=>this._OnMessageFromRuntime(c.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(c=>this.Eb(c));this.T=new self.mb(this);await ma(this.T);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((c,e)=>{window.AndroidFullScreen.immersiveMode(c,
e)})}catch(c){console.error("Failed to enter Android immersive mode: ",c)}this.v?await this.Ab(a,d.port2):await this.zb(a,d.port2)}sa(a){a=this.$.hasOwnProperty(a)?this.$[a]:a.endsWith("/workermain.js")&&this.$.hasOwnProperty("workermain.js")?this.$["workermain.js"]:"playable-ad"===this.g&&this.B.hasOwnProperty(a)?this.B[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ma(a,d,c){if(a.startsWith("blob:"))return new Worker(a,c);if("cordova"===this.g&&this.ya)return a=await this.la(c.Vb?
a:this.I+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),c);a=new URL(a,d);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),c)}return new Worker(a,c)}A(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}Oa(a){var d=this.m,c=location.href,e=this.A(),f=this.u(),g=window.devicePixelRatio,h=b.N(),l=a.jc,m=window.cr_previewImageBlobs||
this.B,n=window.cr_previewProjectFileBlobs,ya=window.cr_previewProjectFiles,za=window.hc||"";a=a.fb;var Aa=(new URLSearchParams(self.location.search)).has("debug"),J=this.T;return{runtimeBaseUrl:d,previewUrl:c,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:l,previewImageBlobs:m,previewProjectFileBlobs:n,previewProjectFileSWUrls:ya,swClientId:za,exportType:a,isDebug:Aa,ife:!!self.ic,jobScheduler:{inputPort:J.xa,outputPort:J.Da,maxNumWorkers:J.Nb},supportedAudioFormats:ea,
opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.I+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.I+"opus.wasm.wasm",isFileProtocol:this.ya,isiOSCordova:this.lb(),isiOSWebView:this.na(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ab(a,d){const c=this.sa(a.cc);"preview"===this.g?(this.L=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,l)=>{const m=n=>{this.L.removeEventListener("message",m);n.data&&"ok"===n.data.type?h():
l()};this.L.addEventListener("message",m);this.L.postMessage({type:"construct-worker-init","import":(new URL(c,this.m)).toString()})})):this.L=await this.ma(c,this.m,{type:"module",name:"Runtime",Vb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.Ha||[],g=a.M;f=await Promise.all(f.map(h=>this.F(h)));g=
await Promise.all(g.map(h=>this.F(h)));if("cordova"===this.g)for(let h=0,l=a.ka.length;h<l;++h){const m=a.ka[h],n=m[0];if(n===a.Ga||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.F(n)}this.L.postMessage(Object.assign(this.Oa(a),{type:"init-runtime",isInWorker:!0,messagePort:d,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ka,mainProjectScript:a.Ga,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[d,e,...na(this.T)]);this.fa=D.map(h=>new h(this));
this.Na();oa(this.Y);self.c3_callFunction=(h,l)=>{var m=this.Y;return m.i.nb(m.R,{name:h,params:l})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.oa("runtime","go-to-last-error-script"))}async zb(a,d){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.fa=D.map(g=>new g(this));this.Na();var c=a.M.map(g=>"string"===typeof g?(new URL(g,this.m)).toString():
g);Array.isArray(a.Ha)&&c.unshift(...a.Ha);c=await Promise.all(c.map(g=>this.F(g)));await Promise.all(c.map(g=>x(g)));c=self.C3_ProjectScriptsStatus;const e=a.Ga,f=a.ka;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.F(h),await x(h),"preview"!==this.g||c[g]||this.Ra(g,"main script did not run to completion")}catch(l){this.Ra(g,l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.F(h),await x(h);"preview"===this.g&&"object"!==typeof self.ec.fc?(this.da(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Oa(a),{isInWorker:!1,messagePort:d,canvas:this.j,runOnStartupFunctions:ja}),oa(this.Y),this.Qa(),this.Ba=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ba,a))}Ra(a,d){this.da();console.error(`[Preview] Failed to load project main script (${a}): `,d);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Qa(){this.da()}da(){const a=
window.Tb;a&&(a.parentElement.removeChild(a),window.Tb=null)}async Cb(){const a=await pa(this.T);return{outputPort:a,transferables:[a]}}yb(){if(this.v)throw Error("not available in worker mode");return this.Ba}oa(a,d,c,e,f){this.V.postMessage({type:"event",component:a,handler:d,dispatchOpts:e||null,data:c,responseId:null},f)}nb(a,d){const c=ia++,e=new Promise((f,g)=>{F.set(c,{resolve:f,reject:g})});this.V.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:d,
responseId:c},void 0);return e}_OnMessageFromRuntime(a){const d=a.type;if("event"===d)return this.Db(a);if("result"===d)this.Gb(a);else if("runtime-ready"===d)this.Hb();else if("alert-error"===d)this.da(),alert(a.message);else if("creating-runtime"===d)this.Qa();else throw Error(`unknown message '${d}'`);}Db(a){const d=a.component,c=a.handler,e=a.data,f=a.responseId;if(a=E.get(d))if(a=a.get(c)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${d}' handler '${c}':`,h);null!==f&&this.ca(f,
!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.ca(f,!0,h)).catch(h=>{console.error(`Rejection from '${d}' handler '${c}':`,h);this.ca(f,!1,""+h)}):this.ca(f,!0,g)}else console.warn(`[DOM] No handler '${c}' for component '${d}'`);else console.warn(`[DOM] No event handlers for component '${d}'`)}ca(a,d,c){let e;c&&c.transferables&&(e=c.transferables);this.V.postMessage({type:"result",responseId:a,isOk:d,result:c},e)}Gb(a){const d=a.responseId,c=a.isOk;a=a.result;const e=F.get(d);c?e.resolve(a):
e.reject(a);F.delete(d)}h(a,d,c){let e=E.get(a);e||(e=new Map,E.set(a,e));if(e.has(d))throw Error(`[DOM] Component '${a}' already has handler '${d}'`);e.set(d,c)}static aa(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}Na(){for(const a of this.fa)if("runtime"===a.R){this.Y=a;return}throw Error("cannot find runtime DOM handler");}Eb(a){this.oa("debugger","message",a)}Hb(){for(const a of this.fa)a.Ia()}static N(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement||la)}static Sa(a){la=!!a}qb(a){this.Ea.push(a);this.ua()}ua(){-1===this.H&&this.Ea.length&&(this.H=requestAnimationFrame(this.Pb))}sb(){-1!==this.H&&(cancelAnimationFrame(this.H),this.H=-1)}Fb(){this.H=-1;for(const a of this.Ea)a();this.ua()}ta(){this.Y.ta()}pb(){this.ab=!0}ib(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}kb(a){return!this.ib(a)}async F(a){return"cordova"===this.g&&(a.startsWith("file:")||this.ya&&this.kb(a))?
(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.la(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Bb(a){const d=a.filename;switch(a.as){case "text":return await this.gb(d);case "buffer":return await this.la(d);default:throw Error("unsupported type");}}Ja(a){const d=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((c,e)=>{window.resolveLocalFileSystemURL(d,f=>{f.file(c,e)},e)})}async gb(a){a=await this.Ja(a);return await fa(a)}qa(){if(B.length&&
!(8<=C)){C++;var a=B.shift();this.vb(a.filename,a.ac,a.Ub)}}la(a){return new Promise((d,c)=>{B.push({filename:a,ac:e=>{C--;this.qa();d(e)},Ub:e=>{C--;this.qa();c(e)}});this.qa()})}async vb(a,d,c){try{const e=await this.Ja(a),f=await ha(e);d(f)}catch(e){c(e)}}Jb(){var a={type:"ready"};if("windows-webview2"===this.g)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.g)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");
}async ub(){const a=[];for(const [d,c]of Object.entries(this.B))a.push(this.tb(d,c));await Promise.all(a)}async tb(a,d){if("object"===typeof d)this.B[a]=new Blob([d.str],{type:d.type}),this.ha[a]=d.str;else{let c=await this.xb(d);c||(c=this.wb(d));this.B[a]=c}}async xb(a){try{return await (await fetch(a)).blob()}catch(d){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
d),null}}wb(a){a=this.Ib(a);return this.rb(a.data,a.Xb)}Ib(a){var d=a.indexOf(",");if(0>d)throw new URIError("expected comma in data: uri");var c=a.substring(d+1);d=a.substring(5,d).split(";");a=d[0]||"";const e=d[2];c="base64"===d[1]||"base64"===e?atob(c):decodeURIComponent(c);return{Xb:a,data:c}}rb(a,d){var c=a.length;let e=c>>2,f=new Uint8Array(c),g=new Uint32Array(f.buffer,0,e),h,l;for(l=h=0;h<e;++h)g[h]=a.charCodeAt(l++)|a.charCodeAt(l++)<<8|a.charCodeAt(l++)<<16|a.charCodeAt(l++)<<24;for(c&=
3;c--;)f[l]=a.charCodeAt(l),++l;return new Blob([f],{type:d})}};"use strict";const G=self.O;function qa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const ra=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),H={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},sa={dispatchUserScriptEvent:!0},I={dispatchRuntimeEvent:!0};
function ta(b){return new Promise((a,d)=>{const c=document.createElement("link");c.onload=()=>a(c);c.onerror=e=>d(e);c.rel="stylesheet";c.href=b;document.head.appendChild(c)})}function ua(b){return new Promise((a,d)=>{const c=new Image;c.onload=()=>a(c);c.onerror=e=>d(e);c.src=b})}async function K(b){b=URL.createObjectURL(b);try{return await ua(b)}finally{URL.revokeObjectURL(b)}}
function va(b){return new Promise((a,d)=>{let c=new FileReader;c.onload=e=>a(e.target.result);c.onerror=e=>d(e);c.readAsText(b)})}
async function wa(b,a,d){if(!/firefox/i.test(navigator.userAgent))return await K(b);var c=await va(b);c=(new DOMParser).parseFromString(c,"image/svg+xml");const e=c.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",d+"px");c=(new XMLSerializer).serializeToString(c);b=new Blob([c],{type:"image/svg+xml"});return await K(b)}
function L(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const xa=new Set(["input","textarea","datalist","select"]),Ba=new Set(["canvas","body","html"]);function M(b){Ba.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ca(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,d,c,e){b=await wa(b,a,d);const f=document.createElement("canvas");f.width=c;f.height=e;f.getContext("2d").drawImage(b,0,0,a,d);return f};
let N=!1;document.addEventListener("pause",()=>N=!0);document.addEventListener("resume",()=>N=!1);function oa(b){b.Ya=!0;b.Aa=b.i.A();b.U=b.i.u()}async function Da(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ea(b){return await self.C3_GetSvgImageSize(b.blob)}
function Fa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ga(b){self.setTimeout(()=>{b.Xa=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>P(b,!0)),document.addEventListener("resume",()=>P(b,!1))):document.addEventListener("visibilitychange",()=>P(b,document.hidden));return{isSuspended:!(!document.hidden&&!N)}}
function Ha(b){b.Ua||(b.Ua=!0,window.addEventListener("deviceorientation",a=>{b.l||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},H)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},H)}))}
function Ia(b){b.Ta||(b.Ta=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var d=null,c=a.acceleration;c&&(d={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var e=a.accelerationIncludingGravity;e&&(c={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:d,accelerationIncludingGravity:c,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},H)}}))}async function Ja(b){await ta(b.url)}
function Ka(b,a){b.Za=a.message;-1===b.wa&&(b.wa=setTimeout(()=>{b.wa=-1;const d=document.getElementById("exportToVideoMessage");d&&(d.textContent=b.Za)},250))}function Q(b){if(!b.l){var a=G.N();a&&"any"!==b.Fa&&La(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.A(),innerHeight:b.u()})}}function R(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:G.N(),innerWidth:b.A(),innerHeight:b.u()})}
function P(b,a){a?b.i.sb():b.i.ua();k(b,"visibilitychange",{hidden:a})}function Ma(b,a,d){"Backspace"===d.key&&M(d);if(!b.l){var c=ra.get(d.code)||d.code;p(b,a,{code:c,key:d.key,which:d.which,repeat:d.repeat,altKey:d.altKey,ctrlKey:d.ctrlKey,metaKey:d.metaKey,shiftKey:d.shiftKey,timeStamp:d.timeStamp},H)}}
function S(b,a,d,c){b.l||qa(d)||p(b,a,{button:d.button,buttons:d.buttons,clientX:d.clientX,clientY:d.clientY+b.o,pageX:d.pageX,pageY:d.pageY+b.o,movementX:d.movementX||0,movementY:d.movementY||0,timeStamp:d.timeStamp},c)}function T(b){window!==window.top&&window.focus();Na(b.target)&&document.activeElement&&!Na(document.activeElement)&&document.activeElement.blur()}
function U(b,a,d){if(!b.l){if(b.X&&"pointermove"!==a){var c=b.X;c.S||(-1!==c.K&&(self.clearTimeout(c.K),c.K=-1),c.ga=Date.now())}c=0;"mouse"===d.pointerType&&(c=b.W);p(b,a,{pointerId:d.pointerId,pointerType:d.pointerType,button:d.button,buttons:d.buttons,lastButtons:c,clientX:d.clientX,clientY:d.clientY+b.o,pageX:d.pageX,pageY:d.pageY+b.o,movementX:(d.movementX||0)+b.ia,movementY:(d.movementY||0)+b.ja,width:d.width||0,height:d.height||0,pressure:d.pressure||0,tangentialPressure:d.tangentialPressure||
0,tiltX:d.tiltX||0,tiltY:d.tiltY||0,twist:d.twist||0,timeStamp:d.timeStamp},H);b.ia=0;b.ja=0;"mouse"===d.pointerType&&(c="mousemove","pointerdown"===a?c="mousedown":"pointerup"===a&&(c="mouseup"),S(b,c,d,sa),b.W=d.buttons)}}
function V(b,a,d){if(!b.l&&!qa(d)){var c=b.W;"pointerdown"===a&&0!==c?a="pointermove":"pointerup"===a&&0!==d.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:d.button,buttons:d.buttons,lastButtons:c,clientX:d.clientX,clientY:d.clientY+b.o,pageX:d.pageX,pageY:d.pageY+b.o,movementX:d.movementX||0,movementY:d.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:d.timeStamp},H);b.W=d.buttons;S(b,d.type,d,sa)}}
function W(b,a,d){if(!b.l)for(let c=0,e=d.changedTouches.length;c<e;++c){const f=d.changedTouches[c];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.o,pageX:f.pageX,pageY:f.pageY+b.o,movementX:d.movementX||0,movementY:d.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:d.timeStamp},
H)}}function X(b,a,d){document.body.style.transform="";b.o=0;if(0<d){var c=document.activeElement;c&&(c=c.getBoundingClientRect(),a=(c.top+c.bottom)/2-(a-d)/2,a>d&&(a=d),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.o=a))}}function Oa(b,a,d,c){const e=b.A(),f=b.u();b.J=-1;e!=a||f!=d?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.N()}):10>c&&Pa(b,e,f,c+1)}
function Pa(b,a,d,c){-1!==b.J&&clearTimeout(b.J);b.J=setTimeout(()=>Oa(b,a,d,c),48)}
function La(b){b=b.Fa;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Na(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
G.aa(class extends self.ba{constructor(b){super(b,"runtime");this.bb=!0;this.Ya=!1;this.J=-1;this.Fa="any";this.Ta=this.Ua=!1;this.D=null;this.l=!1;this.Za="";this.wa=-1;this.G=this.X=null;this.ja=this.ia=0;this.Xa=!1;this.Aa=b.A();this.U=b.u();this.o=this.Z=0;b.h("canvas","update-size",c=>{var e=this.i;e.ab||(e=e.j,e.style.width=c.styleWidth+"px",e.style.height=c.styleHeight+"px",e.style.marginLeft=c.marginLeft+"px",e.style.marginTop=c.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",
c.displayScale),this.bb&&(e.style.display="",this.bb=!1))});b.h("runtime","invoke-download",c=>{const e=c.url;c=c.filename;const f=document.createElement("a"),g=document.body;f.textContent=c;f.href=e;f.download=c;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","raster-svg-image",c=>Da(c));b.h("runtime","get-svg-image-size",c=>Ea(c));b.h("runtime","set-target-orientation",c=>{this.Fa=c.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime",
"post-to-debugger",c=>Fa(c));b.h("runtime","go-to-script",c=>Fa(c));b.h("runtime","before-start-ticking",()=>Ga(this));b.h("runtime","debug-highlight",c=>{if(c.show){this.D||(this.D=document.createElement("div"),this.D.id="inspectOutline",document.body.appendChild(this.D));var e=this.D;e.style.display="";e.style.left=c.left-1+"px";e.style.top=c.top-1+"px";e.style.width=c.width+2+"px";e.style.height=c.height+2+"px";e.textContent=c.name}else this.D&&(this.D.style.display="none")});b.h("runtime","enable-device-orientation",
()=>Ha(this));b.h("runtime","enable-device-motion",()=>Ia(this));b.h("runtime","add-stylesheet",c=>Ja(c));b.h("runtime","script-create-worker",c=>{const e=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",c=>{alert(c.message)});b.h("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",c=>{this.l=!0;const e=document.createElement("h1");
e.id="exportToVideoMessage";e.textContent=c.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.pb()});b.h("runtime","export-to-video-progress",c=>Ka(this,c));b.h("runtime","exported-to-video",c=>{window.Sb({type:"exported-video",blob:c.blob,time:c.time})});b.h("runtime","exported-to-image-sequence",c=>{window.Sb({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);
window.addEventListener("contextmenu",c=>{const e=c.target;a.has(e.tagName.toLowerCase())||L(e)||c.preventDefault()});const d=b.j;window.addEventListener("selectstart",M);window.addEventListener("gesturehold",M);d.addEventListener("selectstart",M);d.addEventListener("gesturehold",M);window.addEventListener("touchstart",M,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",M,{passive:!1}),d.addEventListener("pointerdown",M)):d.addEventListener("touchstart",M);this.W=
0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ca,{passive:!1});window.addEventListener("wheel",Ca,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.Ya){var c=this.A();var e=this.u();if(this.i.La()){if(this.Xa){if(this.Aa===c&&e<this.U){this.Z=this.U-e;X(this,this.U,this.Z);c=void 0;break a}0<this.Z&&(this.Z=0,X(this,e,this.Z))}this.Aa=c;this.U=e}k(this,"window-resize",{innerWidth:c,innerHeight:e,devicePixelRatio:window.devicePixelRatio,
isFullscreen:G.N()});this.i.na()&&(-1!==this.J&&clearTimeout(this.J),Oa(this,c,e,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>Q(this));window.addEventListener("webkitfullscreenchange",()=>Q(this));window.addEventListener("mozfullscreenchange",()=>Q(this));window.addEventListener("fullscreenerror",c=>R(this,c));window.addEventListener("webkitfullscreenerror",c=>R(this,c));window.addEventListener("mozfullscreenerror",c=>R(this,c));if(b.na())if(window.visualViewport){let c=
Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>c&&(document.scrollingElement.scrollTop=0);c=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var c=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?e.has(f.type.toLowerCase()||"text"):L(f)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>{"entered-fullscreen"===
c?(G.Sa(!0),Q(this)):"exited-fullscreen"===c?(G.Sa(!1),Q(this)):console.warn("Unknown wrapper message: ",c)};this.Ca=new Set;this.Ob=new WeakSet;this.Mb=!1}Ia(){window.addEventListener("focus",()=>{k(this,"window-focus",null,I)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(d){a=!1}k(this,"window-blur",{parentHasFocus:a},I);this.W=0});window.addEventListener("focusin",a=>{a=a.target;(xa.has(a.tagName.toLowerCase())||L(a))&&k(this,"keyboard-blur",
null,I)});window.addEventListener("keydown",a=>Ma(this,"keydown",a));window.addEventListener("keyup",a=>Ma(this,"keyup",a));window.addEventListener("dblclick",a=>S(this,"dblclick",a,H));window.addEventListener("wheel",a=>{this.l||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.o,pageX:a.pageX,pageY:a.pageY+this.o,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},H)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{T(a);
U(this,"pointerdown",a)}),this.i.v&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.X=new self.ob(()=>{U(this,"pointermove",this.G);this.G=null}),this.X.Wa=!0,window.addEventListener("pointerrawupdate",a=>{this.G&&(this.ia+=this.G.movementX||0,this.ja+=this.G.movementY||0);this.G=a;a=this.X;if(-1===a.K){var d=Date.now(),c=d-a.ga,e=a.Lb;c>=e&&a.Wa?(a.ga=d,a.S=!0,a.Va(),a.S=!1):a.K=self.setTimeout(a.Rb,Math.max(e-c,4))}})):window.addEventListener("pointermove",a=>U(this,"pointermove",
a)),window.addEventListener("pointerup",a=>U(this,"pointerup",a)),window.addEventListener("pointercancel",a=>U(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{T(a);V(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>V(this,"pointermove",a)),window.addEventListener("mouseup",a=>V(this,"pointerup",a)),window.addEventListener("touchstart",a=>{T(a);W(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>W(this,"pointermove",a)),window.addEventListener("touchend",
a=>W(this,"pointerup",a)),window.addEventListener("touchcancel",a=>W(this,"pointercancel",a)));const b=()=>this.ta();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.jb()&&!this.i.La()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{X(this,this.u(),
navigator.virtualKeyboard.boundingRect.height)}))}A(){return this.i.A()}u(){return this.i.u()}ta(){var b=[...this.Ca];this.Ca.clear();if(!this.Mb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Ob.has(a)||this.Ca.add(a)})}});"use strict";
async function ma(b){if(b.Kb)throw Error("already initialised");b.Kb=!0;var a=b.C.sa(("playable-ad"===b.C.g?b.C.I:"")+"dispatchworker.js");b.va=await b.C.ma(a,b.P,{name:"DispatchWorker"});a=new MessageChannel;b.xa=a.port1;b.va.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Da=await pa(b)}function na(b){return[b.xa,b.Da]}
async function pa(b){const a=b.eb.length;var d=b.C.sa(("playable-ad"===b.C.g?b.C.I:"")+"jobworker.js");d=await b.C.ma(d,b.P,{name:"JobWorker"+a});const c=new MessageChannel,e=new MessageChannel;b.va.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);d.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":e.port2},[c.port2,e.port2]);b.eb.push(d);return e.port1}
self.mb=class{constructor(b){this.C=b;this.P=b.m;this.P="preview"===b.g?this.P+"workers/":this.P+b.I;this.Nb=Math.min(navigator.hardwareConcurrency||2,16);this.va=null;this.eb=[];this.Da=this.xa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.O({bc:!0,cc:"workermain.js",M:["scripts/c3runtime.js"],ka:[],Ga:"",Zb:"scripts/",Ha:[],fb:"html5"}));"use strict";
self.O.aa(class extends self.ba{constructor(b){super(b,"mouse");r(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.i.j.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";let Qa=!1;async function Ra(b){var a=Sa(b.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:b.duration,startDelay:0,weakMagnitude:b.weakMag,strongMagnitude:b.strongMag})}catch(d){console.warn("[Gamepad] Failed to vibrate gamepad: ",d)}}function Y(){try{return Array.from(navigator.getGamepads()).filter(b=>b&&b.connected)}catch(b){return Qa||(console.warn("[Construct] Failed to access gamepads: ",b),Qa=!0),[]}}
function Sa(b){for(const a of Y())if(a.index===b)return a;return null}
self.O.aa(class extends self.ba{constructor(b){super(b,"gamepad");this.cb=!!navigator.getGamepads;this.za=!1;q(this,"is-supported",()=>this.cb);q(this,"ready",()=>{this.za=!0;for(const a of Y())k(this,"gamepad-connected",{index:a.index,id:a.id});this.cb&&!this.$a&&(this.i.qb(this.Qb),this.$a=!0)});q(this,"vibrate",a=>Ra(a));q(this,"reset-vibrate",a=>{(a=Sa(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.za&&(a=a.gamepad,k(this,"gamepad-connected",
{index:a.index,id:a.id}))});window.addEventListener("gamepaddisconnected",a=>{this.za&&k(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of Y()){const d=a.vibrationActuator;d&&d.reset&&d.reset()}})}Ma(){var b=Y();b.length&&(b=b.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(d=>({pressed:d.pressed,value:d.value})),axes:a.axes})),k(this,"input-update",b))}});"use strict";function Z(b){b.stopPropagation()}
self.O.aa(class extends self.hb{constructor(b){super(b)}Ka(b,a){const d=document.createElement("input");var c=d;a.isCheckbox?(d.type="checkbox",c=document.createElement("label"),c.appendChild(d),c.appendChild(document.createTextNode("")),c.style.fontFamily="sans-serif",c.style.userSelect="none",c.style.webkitUserSelect="none",c.style.display="inline-block",c.style.color="black"):d.type="button";c.style.position="absolute";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",
Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("keydown",Z);c.addEventListener("keyup",Z);d.addEventListener("click",()=>{var e={isChecked:d.checked};e.elementId=b;p(this,"click",e)});a.id&&(d.id=a.id);a.className&&(d.className=a.className);this.pa(c,a);return c}ra(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}pa(b,a){const d="input"===b.tagName.toLowerCase()?b:b.firstChild;d.checked=a.isChecked;d.disabled=!a.isEnabled;
b.title=a.title;b===d?d.value=a.text:b.lastChild.textContent=a.text}});
