function m(b,a,c,d){b.j.pb(b.sb,a,c,d)}function n(b,a,c,d){b.j.da?m(b,a,c,d):b.j.We()._OnMessageFromDOM({type:"event",component:b.sb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.j.B(b.sb,a,c)}function v(b,a){for(const [c,d]of a)p(b,c,d)}function w(b){b.Xb||(b.j.Cc(b.me),b.Xb=!0)}window.Qa=class{constructor(b,a){this.j=b;this.sb=a;this.Xb=!1;this.me=()=>this.Fa()}td(){}Fa(){}};
window.Hf=class{constructor(){this.od=-1}l(){-1!==this.od&&(self.clearTimeout(this.od),this.od=-1)}};"use strict";class aa{constructor(b){this.vb=b;this.Uc=!1;this.bd=!0;this.xb=this.ra=this.pd=-1}}
function ba(b,a){const c=a.elementId,d=b.xd(c,a),e=new aa(d);b.La.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.bd=!!a.isVisible;var f=b.Fc(d);f.addEventListener("focus",()=>{ca(b,"elem-focused",c)});f.addEventListener("blur",()=>{ca(b,"elem-blurred",c)});f=a.htmlIndex;e.pd=f;e.xb=a.htmlZIndex;b.Va&&(a=b.j.tc(f),e.ra=a,b.j.Mb(a).appendChild(d))}function da(b,a){p(b,"get-element",c=>{const d=x(b,c.elementId);return a(d,c)})}
function x(b,a){b=b.La.get(a);if(!b)throw Error(`no element with id ${a}`);return b.vb}function ca(b,a,c){var d;d||(d={});d.elementId=c;m(b,a,d)}
window.sc=class extends self.Qa{constructor(b){super(b,"button");this.La=new Map;this.Va=!0;v(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const c=x(this,a);this.Va&&c.parentElement.removeChild(c);this.La.delete(a)}],["set-visible",a=>{if(this.Va){var c=this.La.get(a.elementId),d=c.vb;c.Uc?d.style.display=a.isVisible?"":"none":c.bd=!!a.isVisible}}],["update-position",a=>{if(this.Va){var c=this.La.get(a.elementId),d=c.vb,e=this.j;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";var f=a.fontSize;null!==f&&(d.style.fontSize=f+"em");f=a.htmlIndex;c.pd=f;f=e.tc(f);f!==c.ra&&(d.remove(),e.Mb(f).appendChild(d),c.ra=f,e.Oc());a=a.htmlZIndex;a!==c.xb&&(c.xb=a,e.Oc());c.Uc||(c.Uc=!0,c.bd&&(d.style.display=""))}}],["update-state",a=>{const c=x(this,a.elementId);this.Bc(c,a)}],["focus",a=>this.Lc(a)],["set-css-style",a=>{const c=x(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",
a=>{x(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{x(this,a.elementId).removeAttribute(a.name)}]]);da(this,a=>a)}xd(){throw Error("required override");}Bc(){throw Error("required override");}Fc(b){return b}Lc(b){const a=this.Fc(x(this,b.elementId));b.focus?a.focus():a.blur()}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent);let fa=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.xf?new Promise(c=>{const d="c3_resolve_"+fa;++fa;self[d]=c;a.textContent=b.Bf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ha(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let A=new Audio;
const ia={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}
function ka(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let D=0;window.RealFile=window.File;const F=[],la=new Map,ma=new Map;let na=0;const ra=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ra.push(b)};const sa=new Set(["cordova","playable-ad","instant-games"]);let ta=!1;
window.pa=class b{constructor(a){this.da=a.Df;this.za=null;this.aa="";this.fb=a.Af;this.Kb={};this.Za=this.wa=null;this.Xa=[];this.ma=null;this.Zd=!0;this.M=[];this.hd=[];this.jd=!1;this.ne=()=>this.Ue();this.Yc=!1;this.Td=0;this.zb=null;this.eb=-1;this.tf=()=>this.ef();this.Hb=new Set;this.qd=null;this.oe=[];this.u=a.pe;this.Yb="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.da=!1;if("cordova"===this.u&&this.da&&y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.da=!1)}this.oa()?self.chrome.webview.addEventListener("message",c=>this.Jd(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Jd(c));this.ac=this.ta=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.jf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.$e());this.B("runtime","cordova-fetch-local-file",c=>this.af(c));this.B("runtime","create-job-worker",()=>this.bf());this.B("runtime","send-wrapper-extension-message",c=>this.hf(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.Hd(a)):this.Hd(a)}l(){this.Dc();this.za&&(this.za=this.za.onmessage=null);this.wa&&(this.wa.terminate(),this.wa=null);this.Za&&(this.Za.l(),this.Za=null);for(const {canvas:a,
ib:c}of this.M)a.remove(),c.remove();this.M.length=0}zd(){return this.M[0].canvas}tc(a){return Math.min(a,this.M.length-1)}Mb(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].ib}Ke(){return ea&&"cordova"===this.u}nb(){const a=navigator.userAgent;return ea&&sa.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Ie(){return y}Ad(){return y&&sa.has(this.u)}Cd(){return"windows-webview2"===this.u||!!("preview"===this.u&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}oa(){return this.Cd()||"xbox-uwp-webview2"===this.u}async Hd(a){this.da&&!await ha()&&(this.da=!1);"macos-wkwebview"===this.u?this.Ha({type:"ready"}):this.oa()&&(this.lf(),this.oe=(await this.Ze()).registeredComponentIds);if("playable-ad"===this.u){this.ta=self.c3_base64files;this.ac={};await this.Re();for(let d=0,e=a.hb.length;d<e;++d){var c=a.hb[d];this.ac.hasOwnProperty(c)?a.hb[d]={xf:!0,Bf:this.ac[c]}:this.ta.hasOwnProperty(c)&&(a.hb[d]=URL.createObjectURL(this.ta[c]))}a.pc=
[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Cc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.zf?this.aa=a.zf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Ff&&(this.Kb=a.Ff);c=new MessageChannel;this.za=c.port1;this.za.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.df(d));this.zb=
new self.Le(this);await ua(this.zb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.da?await this.Ye(a,c.port2):await this.Xe(a,c.port2)}Gc(a){a=this.Kb.hasOwnProperty(a)?this.Kb[a]:a.endsWith("/workermain.js")&&this.Kb.hasOwnProperty("workermain.js")?this.Kb["workermain.js"]:"playable-ad"===
this.u&&this.ta.hasOwnProperty(a)?this.ta[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async rc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.Yb)return a=await this.Lb(d.wf?a:this.fb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}qa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}Gd(a){var c=this.aa,d=location.href,e=this.qa(),f=this.ga(),g=window.devicePixelRatio,h=b.mb(),k=a.Lf,l=window.cr_previewImageBlobs||this.ta,q=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.pe;var u=(new URLSearchParams(self.location.search)).has("debug"),B=this.zb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:q,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Kf,jobScheduler:{inputPort:B.Xc,outputPort:B.gd,maxNumWorkers:B.qf},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.fb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.fb+"opus.wasm.wasm",isFileProtocol:this.Yb,isiOSCordova:this.Ke(),isiOSWebView:this.nb(),isWindowsWebView2:this.Cd(),isAnyWebView2Wrapper:this.oa(),wrapperComponentIds:this.oe,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ye(a,c){const d=this.Gc(a.Ef);"preview"===this.u?(this.wa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,q)=>{const r=t=>{this.wa.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():q()};this.wa.addEventListener("message",r);this.wa.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.wa=await this.rc(d,this.aa,{type:"module",name:"Runtime",wf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,ib:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.pc||[],k=a.hb;h=await Promise.all(h.map(l=>this.Ta(l)));k=await Promise.all(k.map(l=>this.Ta(l)));if("cordova"===this.u)for(let l=0,q=a.oc.length;l<q;++l){const r=
a.oc[l],t=r[0];if(t===a.rd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Ta(t)}this.wa.postMessage(Object.assign(this.Gd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.oc,mainProjectScript:a.rd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...va(this.zb)]);this.Xa=F.map(l=>new l(this));this.Fd();wa(e);xa(g);ya(this.ma);self.c3_callFunction=(l,q)=>{var r=this.ma;return r.j.Dd(r.sb,"js-invoke-function",
{name:l,params:q})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.pb("runtime","go-to-last-error-script"))}async Xe(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,ib:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Xa=F.map(h=>new h(this));this.Fd();wa(d);xa(e);e=a.hb.map(h=>"string"===
typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.pc)){var f=[...a.pc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Ta(h)));await Promise.all(e.map(h=>z(h)));e=self.C3_ProjectScriptsStatus;f=a.rd;const g=a.oc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ta(k),await z(k),"preview"!==this.u||e[h]||this.Ld(h,"main script did not run to completion")}catch(l){this.Ld(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Ta(k),await z(k);"preview"===this.u&&"object"!==typeof self.Gf.If?(this.Rb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Gd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:ra}),ya(this.ma),this.Id(),this.Za=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Za,
a))}Ld(a,c){this.Rb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Id(){this.Rb()}Rb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async bf(){const a=await za(this.zb);return{outputPort:a,transferables:[a]}}jf(a){if(!this.Yc){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,ib:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Zd&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Zd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,ib:q}=this.M.pop();q.remove();this.da&&!d?this.hd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,q=c-this.M.length;l<q;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.da?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,wa(c),xa(d),this.M.push({canvas:c,ib:d});for(const l of this.Xa)if(l instanceof window.sc&&l.Va)for(const q of l.La.values())e=l.j.tc(q.pd),f=q.ra,-1!==e&&-1!==f&&e!==f&&(f=q.vb,f.remove(),l.j.Mb(e).appendChild(f),q.ra=e);this.Oc();return{addedCanvases:a,transferables:k}}$e(){for(const a of this.hd)a.remove();this.hd.length=0}Oc(){this.jd||(this.jd=!0,this.Cc(this.ne))}Ue(){this.Kd(this.ne);
this.jd=!1;let a=[];for(var c of this.Xa)if(c instanceof window.sc){var d=c.Va?[...c.La.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.ra,l=h.ra;return k!==l?k-l:g.xb-h.xb});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.ra!==c&&(this.Ed(c,a.slice(d,e)),c=g.ra,d=e)}d<e&&this.Ed(c,a.slice(d,e))}Ed(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.vb);var d=new Set(c);a=this.Mb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}We(){if(this.da)throw Error("not available in worker mode");return this.Za}pb(a,c,d,e,f){this.za.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}Dd(a,c,d,e,f){const g=na++,h=new Promise((k,l)=>{ma.set(g,{resolve:k,reject:l})});this.za.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.cf(a);if("result"===c)this.ff(a);else if("runtime-ready"===c)this.gf();else if("alert-error"===c)this.Rb(),alert(a.message);else if("creating-runtime"===c)this.Id();else throw Error(`unknown message '${c}'`);}cf(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=la.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Qb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Qb(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Qb(f,!1,""+h)}):this.Qb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Qb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.za.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}ff(a){const c=a.responseId,d=a.isOk;a=a.result;const e=ma.get(c);d?e.resolve(a):e.reject(a);ma.delete(c)}B(a,c,d){let e=la.get(a);e||(e=new Map,la.set(a,
e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Pa(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}Fd(){for(const a of this.Xa)if("runtime"===a.sb){this.ma=a;return}throw Error("cannot find runtime DOM handler");}df(a){this.pb("debugger","message",a)}gf(){for(const a of this.Xa)a.td()}static mb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ta)}static Sb(a){ta=!!a}Cc(a){this.Hb.add(a);
this.Nc()}Kd(a){this.Hb.delete(a);0===this.Hb.size&&this.Dc()}Nc(){-1===this.eb&&0<this.Hb.size&&(this.eb=requestAnimationFrame(this.tf))}Dc(){-1!==this.eb&&(cancelAnimationFrame(this.eb),this.eb=-1)}ef(){this.eb=-1;for(const a of this.Hb)a();this.Nc()}Ga(a){this.ma.Ga(a)}Sa(a){this.ma.Sa(a)}Mc(){this.ma.Mc()}Pb(a){this.ma.Pb(a)}Je(){return!!ia["audio/webm; codecs=opus"]}async mf(a){a=await this.Dd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ne(a){this.Yc=!0;this.Td=
a}He(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Bd(a){return!this.He(a)}async Ta(a){return"cordova"===this.u&&(a.startsWith("file:")||this.Yb&&this.Bd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Lb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async af(a){const c=a.filename;switch(a.as){case "text":return await this.Ge(c);case "buffer":return await this.Lb(c);default:throw Error("unsupported type");
}}wd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Ge(a){a=await this.wd(a);return await ja(a)}Ec(){if(C.length&&!(8<=D)){D++;var a=C.shift();this.Se(a.filename,a.Cf,a.vf)}}Lb(a){return new Promise((c,d)=>{C.push({filename:a,Cf:e=>{D--;this.Ec();c(e)},vf:e=>{D--;this.Ec();d(e)}});this.Ec()})}async Se(a,c,d){try{const e=await this.wd(a),f=await ka(e);c(f)}catch(e){d(e)}}Jd(a){if("entered-fullscreen"===
a)b.Sb(!0),G(this.ma);else if("exited-fullscreen"===a)b.Sb(!1),G(this.ma);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.qd(a),this.qd=null):"extension-message"===c?this.pb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}hf(a){this.Ha({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ha(a){this.oa()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}lf(){window.moveTo=(a,c)=>{this.Ha({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ha({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Ze(){return this.oa()?new Promise(a=>{this.qd=a;this.Ha({type:"wrapper-init"})}):Promise.resolve()}async Re(){const a=[];for(const [c,d]of Object.entries(this.ta))a.push(this.Qe(c,d));
await Promise.all(a)}async Qe(a,c){if("object"===typeof c)this.ta[a]=new Blob([c.str],{type:c.type}),this.ac[a]=c.str;else{let d=await this.Ve(c);d||(d=this.Te(c));this.ta[a]=d}}async Ve(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Te(a){a=this.kf(a);return this.Pe(a.data,
a.yf)}kf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{yf:a,data:d}}Pe(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const H=self.pa,Aa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ba={dispatchUserScriptEvent:!0},Ca={dispatchRuntimeEvent:!0};function Da(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ea(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function J(b){b=URL.createObjectURL(b);try{return await Ea(b)}finally{URL.revokeObjectURL(b)}}function Fa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ga(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await Fa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Ha(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ia=new Set(["input","textarea","datalist","select"]),Ja=new Set(["canvas","body","html"]);function K(b){b.target.tagName&&Ja.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ka(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function La(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ga(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ma=!1;document.addEventListener("pause",()=>Ma=!0);document.addEventListener("resume",()=>Ma=!1);function wa(b){b.addEventListener("selectstart",K);b.addEventListener("gesturehold",K);b.addEventListener("pointerdown",K)}function xa(b){b.addEventListener("selectstart",Ka);b.addEventListener("gesturehold",Ka);b.addEventListener("touchstart",Ka)}function ya(b){b.Sd=!0;b.cd=b.j.qa();b.Ab=b.j.ga()}
function G(b){if(!b.ka){var a=H.mb();a&&"any"!==b.md&&Na(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ga()})}}async function Oa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Pa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ra(b){return await self.C3_GetSvgImageSize(b.blob)}function Sa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ta(b){self.setTimeout(()=>{b.Rd=!0},1E3);"cordova"===b.j.u?(document.addEventListener("pause",()=>Ua(b,!0)),document.addEventListener("resume",()=>Ua(b,!1))):document.addEventListener("visibilitychange",()=>Ua(b,"hidden"===document.visibilityState));b.ec=!("hidden"!==document.visibilityState&&!Ma);return{isSuspended:b.ec}}
function Va(b){b.Nd||(b.Nd=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Wa(b){b.Md||(b.Md=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Xa(b){await Da(b.url)}
function Ya(b,a){b.Ud=a.message;-1===b.Sc&&(b.Sc=setTimeout(()=>{b.Sc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Ud)},250))}function Za(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:H.mb(),innerWidth:b.qa(),innerHeight:b.ga()})}
function Ua(b,a){b.ec!==a&&((b.ec=a)?b.j.Dc():b.j.Nc(),m(b,"visibilitychange",{hidden:a}),!a&&b.j.nb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function $a(b,a,c){"Backspace"===c.key&&K(c);if(b.j.oa()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.ka||(d=Aa.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I))}
function L(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Ca,pageX:c.pageX,pageY:c.pageY+b.Ca,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function M(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.ed);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Ca,pageX:c.pageX,pageY:c.pageY+b.Ca,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);"mouse"===c.pointerType&&
(b.ed=c.buttons)}}function ab(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Ca=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Ca=a))}}
function bb(b,a,c,d){const e=b.qa(),f=b.ga();b.gb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.mb()}):10>d&&cb(b,e,f,d+1)}function cb(b,a,c,d){-1!==b.gb&&clearTimeout(b.gb);b.gb=setTimeout(()=>bb(b,a,c,d),48)}
function Na(b){b=b.md;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function db(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.Pa(class extends self.Qa{constructor(b){super(b,"runtime");this.Sd=!1;this.gb=-1;this.md="any";this.ec=this.Md=this.Nd=!1;this.lc=document.createElement("div");this.lc.className="c3-screen-reader-text";this.lc.setAttribute("aria-live","polite");document.body.appendChild(this.lc);this.Ka=null;this.ka=!1;this.Ud="";this.Sc=-1;this.Rd=!1;this.cd=b.qa();this.Ab=b.ga();this.Ca=this.Jb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Oa(c));b.B("runtime","raster-svg-image",c=>Pa(c));b.B("runtime","get-svg-image-size",c=>Ra(c));b.B("runtime","set-target-orientation",c=>{this.md=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Sa(c));b.B("runtime","go-to-script",c=>Sa(c));b.B("runtime","before-start-ticking",()=>Ta(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ka||(this.Ka=document.createElement("div"),this.Ka.id="inspectOutline",document.body.appendChild(this.Ka));var d=this.Ka;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ka&&(this.Ka.style.display="none")});b.B("runtime","enable-device-orientation",()=>Va(this));b.B("runtime","enable-device-motion",()=>Wa(this));b.B("runtime","add-stylesheet",c=>Xa(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Jc(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.lc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.j.zd().style.display="";this.j.Ne(c.duration)});b.B("runtime","export-to-video-progress",c=>Ya(this,c));b.B("runtime","exported-to-video",c=>{window.uf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.uf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ha(d)||c.preventDefault()});window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);window.addEventListener("touchstart",K,{passive:!1});window.addEventListener("pointerdown",K,{passive:!1});this.ed=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",La,{passive:!1});window.addEventListener("wheel",La,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Sd){var c=this.qa();var d=this.ga();if(this.j.Ad()){if(this.Rd){if(this.cd===
c&&d<this.Ab){this.Jb=this.Ab-d;ab(this,this.Ab,this.Jb);c=void 0;break a}0<this.Jb&&(this.Jb=0,ab(this,d,this.Jb))}this.cd=c;this.Ab=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.mb()});this.j.nb()&&(-1!==this.gb&&clearTimeout(this.gb),bb(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>G(this));window.addEventListener("webkitfullscreenchange",()=>G(this));window.addEventListener("mozfullscreenchange",()=>
G(this));window.addEventListener("fullscreenerror",c=>Za(this,c));window.addEventListener("webkitfullscreenerror",c=>Za(this,c));window.addEventListener("mozfullscreenerror",c=>Za(this,c));if(b.nb()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Ha(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.$a=new Set;this.cc=new WeakSet;this.ya=!1}td(){window.addEventListener("focus",()=>{m(this,"window-focus",null,Ca)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},Ca);this.ed=0});window.addEventListener("focusin",a=>{a=a.target;(Ia.has(a.tagName.toLowerCase())||Ha(a))&&m(this,"keyboard-blur",null,Ca)});window.addEventListener("keydown",a=>$a(this,"keydown",a));window.addEventListener("keyup",a=>$a(this,"keyup",a));window.addEventListener("mousedown",a=>L(this,"mousedown",a,Ba));window.addEventListener("mousemove",a=>L(this,"mousemove",a,Ba));window.addEventListener("mouseup",a=>L(this,"mouseup",a,Ba));window.addEventListener("dblclick",
a=>L(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Ca,pageX:a.pageX,pageY:a.pageY+this.Ca,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();db(a.target)&&document.activeElement&&!db(document.activeElement)&&document.activeElement.blur();M(this,"pointerdown",a)});this.j.da&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a));window.addEventListener("pointerup",a=>M(this,"pointerup",a));window.addEventListener("pointercancel",a=>M(this,"pointercancel",a));const b=()=>this.Mc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.j.Ie()&&!this.j.Ad()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{ab(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.j.nb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}qa(){return this.j.qa()}ga(){return this.j.ga()}Mc(){var b=[...this.$a];this.$a.clear();if(!this.ya)for(const a of b)(b=a.play())&&b.catch(()=>{this.cc.has(a)||this.$a.add(a)})}Ga(b){if("function"!==
typeof b.play)throw Error("missing play function");this.cc.delete(b);let a;try{a=b.play()}catch(c){this.$a.add(b);return}a&&a.catch(()=>{this.cc.has(b)||this.$a.add(b)})}Sa(b){this.$a.delete(b);this.cc.add(b)}Pb(b){this.ya=!!b}Jc(b){alert(b.message)}});"use strict";
async function ua(b){if(b.nf)throw Error("already initialised");b.nf=!0;var a=b.Aa.Gc(("playable-ad"===b.Aa.u?b.Aa.fb:"")+"dispatchworker.js");b.Rc=await b.Aa.rc(a,b.rb,{name:"DispatchWorker"});a=new MessageChannel;b.Xc=a.port1;b.Rc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.gd=await za(b)}function va(b){return[b.Xc,b.gd]}
async function za(b){const a=b.ae.length;var c=b.Aa.Gc(("playable-ad"===b.Aa.u?b.Aa.fb:"")+"jobworker.js");c=await b.Aa.rc(c,b.rb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Rc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.ae.push(c);return e.port1}
self.Le=class{constructor(b){this.Aa=b;this.rb=b.aa;this.rb="preview"===b.u?this.rb+"workers/":this.rb+b.fb;this.qf=Math.min(navigator.hardwareConcurrency||2,16);this.Rc=null;this.ae=[];this.gd=this.Xc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.pa({Df:!0,Ef:"workermain.js",hb:["scripts/c3runtime.js"],oc:[],rd:"",Af:"scripts/",pc:[],pe:"html5"}));"use strict";function N(b){b.stopPropagation()}
self.pa.Pa(class extends self.sc{constructor(b){super(b)}xd(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",N);d.addEventListener("pointermove",N);d.addEventListener("pointerrawupdate",
N);d.addEventListener("pointerup",N);d.addEventListener("mousedown",N);d.addEventListener("mouseup",N);d.addEventListener("keydown",N);d.addEventListener("keyup",N);d.addEventListener("contextmenu",e=>e.preventDefault());c.addEventListener("click",()=>{var e={isChecked:c.checked};e.elementId=b;n(this,"click",e)});a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.Bc(d,a);return d}Fc(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}Bc(b,a){const c="input"===b.tagName.toLowerCase()?
b:b.firstChild;c.checked=a.isChecked;c.disabled=!a.isEnabled;b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});"use strict";let eb=!1;async function fb(b){var a=gb(b.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:b.duration,startDelay:0,weakMagnitude:b.weakMag,strongMagnitude:b.strongMag})}catch(c){console.warn("[Gamepad] Failed to vibrate gamepad: ",c)}}
function O(){try{return Array.from(navigator.getGamepads()).filter(b=>b&&b.connected)}catch(b){return eb||(console.warn("[Construct] Failed to access gamepads: ",b),eb=!0),[]}}function gb(b){for(const a of O())if(a.index===b)return a;return null}
self.pa.Pa(class extends self.Qa{constructor(b){super(b,"gamepad");this.$d=!!navigator.getGamepads;this.$c=!1;p(this,"is-supported",()=>this.$d);p(this,"ready",()=>{this.$c=!0;for(const a of O())m(this,"gamepad-connected",{index:a.index,id:a.id});this.$d&&w(this)});p(this,"vibrate",a=>fb(a));p(this,"reset-vibrate",a=>{(a=gb(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.$c&&(a=a.gamepad,m(this,"gamepad-connected",{index:a.index,id:a.id}))});
window.addEventListener("gamepaddisconnected",a=>{this.$c&&m(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of O()){const c=a.vibrationActuator;c&&c.reset&&c.reset()}})}Fa(){var b=O();b.length&&(b=b.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(c=>({pressed:c.pressed,value:c.value})),axes:a.axes})),m(this,"input-update",b))}});"use strict";
self.pa.Pa(class extends self.Qa{constructor(b){super(b,"mouse");v(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.j.zd().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";function hb(){}function ib(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function kb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.pa.Pa(class extends self.Qa{constructor(b){super(b,"browser");this.u="";v(this,[["get-initial-state",a=>{this.u=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
ib(this)],["alert",a=>this.Jc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Lc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>kb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.j.oa()?window.open(c,"_blank"):this.Jf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.j.oa()||"macos-wkwebview"===this.u)self.pa.Sb(!0),this.j.Ha({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(hb)}}],["exit-fullscreen",()=>{if(this.j.oa()||"macos-wkwebview"===this.u)self.pa.Sb(!1),this.j.Ha({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(hb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,
a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}Jc(b){alert(b.message)}Lc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():
null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";const lb=180/Math.PI;
async function mb(b,a){if(a.isiOSCordova||a.isSafari)b.hc=!0;b.nd=a.timeScaleMode;b.fe=["equalpower","HRTF","soundfield"][a.panningModel];b.Qd=["linear","inverse","exponential"][a.distanceModel];b.ge=a.refDistance;b.ee=a.maxDistance;b.ie=a.rolloffFactor;if(b.j.Yc)b.hc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.j.Td)});else{var c={latencyHint:a.latencyHint};b.le||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");nb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&nb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Wa=b.g.createGain();b.Wa.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ba);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function ob(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,q=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.be=g.slice(0);pb(b,g);try{b.R=await qb(b,c,d,e,g,f);if(q){Q(b.R,!0);var u=b.R,B=q.innerAngle,oa=q.outerAngle,qa=q.outerGain;if(u.yb){rb(u,q.x,q.y,q.z,q.angle);var E=self.jb.Oe;u.ua[0]!==E(B)&&
(u.ua[0]=E(B),u.F.coneInnerAngle=E(B));u.ua[1]!==E(oa)&&(u.ua[1]=E(oa),u.F.coneOuterAngle=E(oa));u.ua[2]!==qa&&(u.ua[2]=qa,u.F.coneOuterGain=qa)}q.hasOwnProperty("uid")&&(b.R.sa=q.uid)}else"number"===typeof r&&0!==r?(R(b.R,!0),sb(b.R,r)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,l,t)}catch(Eb){console.error("[Construct] Audio: error starting playback: ",Eb);return}finally{c=g.join(" ");d=b.Gb.get(c);if(!d)throw Error("expected pending tag");d.sd--;0===d.sd&&(d.resolve(),b.Gb.delete(c))}w(b)}
async function tb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await ub(b,c);for(const h of S(b,c))if(!h.xa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Oa=d;h.Ya=g;h.ke=a}T(b)}async function vb(b,a){const c=a.tags;a=a.rate;await ub(b,c);for(const d of S(b,c))d.la!==a&&(d.la=a,d.Ia())}async function wb(b,a){const c=a.tags;a=a.pos;await ub(b,c);for(const d of S(b,c))d.yc(a)}
async function xb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await qb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function yb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.l(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function zb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.ve(b,...e);else if("delay"===c)d=new self.te(b,...e);else if("convolution"===c){var g=d=new self.se(b,f.ha,...e),h=a.bufferType;g.Od=a.bufferOriginalUrl;g.Pd=h}else if("flanger"===c)d=
new self.we(b,...e);else if("phaser"===c)d=new self.ye(b,...e);else if("gain"===c)d=new self.xe(b,...e);else if("stereopan"===c)d=new self.Ae(b,...e);else if("tremolo"===c)d=new self.Be(b,...e);else if("ringmod"===c)d=new self.ze(b,...e);else if("distortion"===c)d=new self.ue(b,...e);else if("compressor"===c)d=new self.re(b,...e);else if("analyser"===c)d=new self.qe(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Yd=l.length;d.ld=
h;l.push(d);Ab(g,h)}Bb(b)}
async function Cb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Da()&&1===c||!e.Da()&&2===c?d.push(e):e.l();b.H=d}for(const f of b.ja.values())for(const g of f)g.l();b.ja.clear();b.mc=a.timeScale;b.Tc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ba[e]=d[e];b.g.listener.setOrientation(...b.ba)}b.ya=a.isSilent;b.j.Pb(b.ya);b.bc=a.masterVolume;b.Wa.gain.value=
b.bc;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>zb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Db(b,f,c)));T(b)}
async function Fb(b,a){try{const c=b.g.suspend(a.time);b.Xd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.j.pb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Gb(d)),b.Xd=!0);await c}catch(c){Gb(c)}}
function nb(b){b.Wb||(b.Wc=!1,window.addEventListener("pointerup",b.Ba,!0),window.addEventListener("touchend",b.Ba,!0),window.addEventListener("click",b.Ba,!0),window.addEventListener("keydown",b.Ba,!0),b.Wb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ia)if(g.lb()===c)return await Hb(g),g;if(f)return null;if(e&&(b.hc||b.Wd)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Da()?g.l():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.le;e&&f&&(b.Wd=!0);c=!e||b.hc||f?new self.Ee(b,a,c,d,e,f):new self.Ce(b,a,c,d,e);b.ia.push(c);await Hb(c);b.de.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.de.add(a));return c}
function Ib(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Jb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function Ab(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Kb(b,a))d=c,e=f.ca||f.F||f.G,e.disconnect(),e.connect(d);b.Ma&&b.dd===a&&(b.Ma.disconnect(),b.Ma.connect(c))}
function*Kb(b,a){if(a)for(const c of b.H)Ib(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Lb(b,a,c){return c?b.j.mf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Mb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.l():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(Ib(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function qb(b,a,c,d,e,f){for(const g of b.H)if(g.lb()===c&&(g.qc()||f))return g.na=e,g;a=await P(b,a,c,d,f);e="html5"===a.Pc?new self.De(a.v,a,e):new self.Fe(a.v,a,e);b.H.push(e);return e}
function pb(b,a){a=a.join(" ");let c=b.Gb.get(a);if(!c){let d=null;c={sd:0,promise:new Promise(e=>d=e),resolve:d};b.Gb.set(a,c)}c.sd++}function ub(b,a){return(b=b.Gb.get((0===a.length?b.be:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Ua.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Nb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function Bb(b){b.Zc||(b.Zc=!0,Promise.resolve().then(()=>Ob(b)))}
function Ob(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.kb());m(b,"fxstate",{fxstate:a});b.Zc=!1}
async function Db(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await qb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.bb[0]=f[0],b.bb[1]=f[1],b.bb[2]=f[2],f=d.orient,b.ab[0]=f[0],b.ab[1]=f[1],b.ab[2]=f[2],e.setPosition(...b.bb),e.setOrientation(...b.ab),b.ua[0]=d.cia,b.ua[1]=d.coa,b.ua[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.sa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),sb(b,d));c.Play(k,l,q,0);a.isPlaying||c.ob();c.Ic(a)}}}function Gb(b){console.error("[Audio] Offline rendering error: ",b)}
self.jb=class extends self.Qa{constructor(b){super(b,"audio");this.Wa=this.g=null;this.Wb=this.Wc=!1;this.Ba=()=>{if(!this.Wc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Wb&&(this.Wc=!0,window.removeEventListener("pointerup",this.Ba,!0),window.removeEventListener("touchend",this.Ba,!0),window.removeEventListener("click",this.Ba,!0),window.removeEventListener("keydown",
this.Ba,!0),this.Wb=!1)}};this.ia=[];this.H=[];this.R=null;this.be=[];this.de=new Set;this.ce=-1;this.Gb=new Map;this.bc=1;this.ya=!1;this.nd=0;this.mc=1;this.Tc=0;this.fe="HRTF";this.Qd="inverse";this.ge=600;this.ee=1E4;this.ie=1;this.$=[0,0,0];this.ba=[0,0,-1,0,1,0];this.Wd=this.hc=!1;this.le=this.j.Je();this.ja=new Map;this.Ua=new Set;this.Xd=this.Zc=!1;this.dd="";this.Ma=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ma&&this.Ma.disconnect();this.dd=c.toLowerCase();this.Ma=this.g.createMediaStreamSource(a);
this.Ma.connect(Jb(this,this.dd))};this.Vb=null;self.C3Audio_GetOutputStream=()=>{this.Vb||(this.Vb=this.g.createMediaStreamDestination(),this.Wa.connect(this.Vb));return this.Vb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>mb(this,a)],["play",a=>ob(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ea()}],["stop-all",()=>{for(const a of this.H)a.Ea()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.ob():d.Ob();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>tb(this,a)],["set-master-volume",a=>{this.bc=a.vol;this.Wa.gain.value=this.bc}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Pb(d,a)}],["set-silent",a=>{this.ya=a.isSilent;this.j.Pb(this.ya);for(const c of this.H)c.Tb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.zc(a)}],["set-playback-rate",a=>vb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),sb(d,a)}],["seek",a=>wb(this,a)],["preload",a=>xb(this,a)],["unload",a=>yb(this,a)],["unload-all",()=>{for(const a of this.ia)a.l();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Ac(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>zb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Bb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.l();this.ja.delete(a);Ab(this,a)}}],["tick",a=>{this.mc=a.timeScale;this.Tc=a.gameTime;this.ce=a.tickCount;if(0!==this.nd)for(var c of this.H)c.Ia();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ba[0]!==
c[0]||this.ba[1]!==c[1]||this.ba[2]!==c[2]||this.ba[3]!==c[3]||this.ba[4]!==c[4]||this.ba[5]!==c[5])){for(let d=0;6>d;++d)this.ba[d]=c[d];this.g.listener.setOrientation(...this.ba)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.sa===a&&rb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Cb(this,a)],["offline-render-audio",a=>Fb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Wa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Nb(){return this.ya}Ga(b){this.j.Ga(b)}Sa(b){this.j.Sa(b)}Fa(){for(var b of this.Ua)b.Fa();
b=this.g.currentTime;for(var a of this.H)a.Fa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.kb());m(this,"state",{tickCount:this.ce,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ua].map(c=>({tag:c.ld,index:c.Yd,peak:c.cb,rms:c.he,binCount:c.m.frequencyBinCount,freqBins:c.Vd}))});0===a.length&&0===this.Ua.size&&this.Xb&&(this.j.Kd(this.me),this.Xb=!1)}static Oe(b){return b*lb}static yd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Me(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.pa.Pa(self.jb);"use strict";function Hb(b){b.$b||(b.$b=b.Hc());return b.$b}self.ud=class{constructor(b,a,c,d,e){this.v=b;this.sf=a;this.Na=c;this.T=d;this.pf=e;this.Pc="";this.$b=null}l(){this.$b=this.v=null}Hc(){}V(){return this.v.V()}vc(){return this.sf}lb(){return this.Na}uc(){return this.T}Da(){return this.pf}fa(){}};"use strict";
self.Ce=class extends self.ud{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Pc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Bb=this.Cb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Fb=this.V().createGain();this.Eb=null;this.L.addEventListener("canplay",()=>{this.Cb&&(this.Cb(),this.Bb=this.Cb=null);!this.Eb&&this.L&&(this.Eb=this.V().createMediaElementSource(this.L),this.Eb.connect(this.Fb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Na}' error: `,f);this.Bb&&(this.Bb(f),this.Bb=this.Cb=null)})}l(){Mb(this.v,this);this.Fb.disconnect();this.Fb=null;this.Eb.disconnect();this.Eb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.l()}Hc(){return new Promise((b,a)=>{this.Cb=b;this.Bb=a;this.L.src=this.Na})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Qb(b){if(b.Ja)return b.Ja;var a=b.v.j;if("cordova"===a.u&&a.Bd(b.Na)&&a.Yb)b.Ja=await a.Lb(b.Na);else{a=await fetch(b.Na);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ja=await a.arrayBuffer()}}async function Rb(b){if(b.ha)return b.ha;b.ha=await Lb(b.v,b.Ja,b.rf);b.Ja=null}
self.Ee=class extends self.ud{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Pc="webaudio";this.ha=this.Ja=null;this.rf=!!f}l(){Mb(this.v,this);this.ha=this.Ja=null;super.l()}async Hc(){try{await Qb(this),await Rb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Na}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Sb=0;
function Q(b,a){a=!!a;b.yb!==a&&(b.yb=a,b.yb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.v.fe,b.F.distanceModel=b.v.Qd,b.F.refDistance=b.v.ge,b.F.maxDistance=b.v.ee,b.F.rolloffFactor=b.v.ie),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function R(b,a){a=!!a;b.Zb!==a&&(b.Zb=a,b.Zb?(Q(b,!1),b.ca=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ca),b.ca.connect(b.ea())):(b.ca.disconnect(),b.ca=null,b.G.disconnect(),b.G.connect(b.ea())))}function sb(b,a){b.Zb&&b.kd!==a&&(b.ca.pan.value=a,b.kd=a)}function U(b,a){b.Oa=a;b.G.gain.cancelScheduledValues(0);b.Ya=-1;b.G.gain.value=b.wc()}function Pb(b,a){a=!!a;b.xa!==a&&(b.xa=a,b.Tb())}
function rb(b,a,c,d,e){if(b.yb){var f=b.bb,g=b.ab,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.ad?b.v.Tc:performance.now()/1E3}
self.vd=class{constructor(b,a,c){this.v=b;this.P=a;this.na=c;this.Ub=Sb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.yb=!1;this.bb=[0,0,0];this.ab=[0,0,0];this.ua=[0,0,0];this.ca=null;this.Zb=!1;this.kd=0;this.I=!0;this.Y=this.va=this.J=!1;this.Oa=1;this.xa=!1;this.la=1;b=this.v.nd;this.ad=1===b&&!this.Da()||2===b;this.Ya=this.sa=-1;this.ke=!1}l(){this.P=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.ca&&(this.ca.disconnect(),this.ca=null);this.G.disconnect();
this.G=null}V(){return this.v.V()}ea(){return Jb(this.v,0<this.na.length?this.na[0]:"")}vc(){return this.P.vc()}lb(){return this.P.lb()}uc(){return this.P.uc()}Da(){return this.P.Da()}O(){}qc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Ra(){}fa(){return this.P.fa()}Play(){}Ea(){}ob(){}Ob(){}Fa(b){-1!==this.Ya&&b>=this.Ya&&(this.Ya=-1,this.ke&&this.Ea(),Nb(this.v,"fade-ended",this.na,this.Ub))}wc(){const b=this.Oa;return isFinite(b)?b:0}Nb(){return this.v.Nb()}Tb(){}zc(){}Ia(){}yc(){}Ac(){}xc(){}kb(){var b=
this.Ub,a=this.na,c=this.fa(),d=-1===this.Ya?this.Oa:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.bb,orient:this.ab,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.sa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ra(),playbackRate:this.la,uid:this.sa,bufferOriginalUrl:this.vc(),bufferUrl:"",bufferType:this.uc(),isMusic:this.Da(),isLooping:this.Y,isMuted:this.xa,resumePosition:this.xc(),pan:f,stereoPan:this.ca?
this.kd:null}}Ic(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Ia());Pb(this,b.isMuted)}};"use strict";
self.De=class extends self.vd{constructor(b,a,c){super(b,a,c);this.P.Fb.connect(this.G);this.P.onended=()=>this.Kc()}l(){this.Ea();this.P.Fb.disconnect();super.l()}W(){return this.P.W()}Kc(){this.I=!0;this.sa=-1;Nb(this.v,"ended",this.na,this.Ub)}O(){return this.W().ended}qc(){return this.I?!0:this.O()}Ra(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);this.xa=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.lb()}' to position '${c}': `,e)}this.v.Ga(d);this.J=this.I=!1;this.Y=b;this.la=1}Ea(){const b=this.W();b.paused||b.pause();this.v.Sa(b);this.I=!0;this.J=!1;this.sa=-1}ob(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.v.Sa(b);this.J=!0}}Ob(){!this.J||this.I||this.O()||(this.v.Ga(this.W()),this.J=!1)}Tb(){this.W().muted=this.xa||this.Nb()}zc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ia(){let b=this.la;this.ad&&(b*=this.v.mc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}yc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}xc(){return this.Ra()}Ac(b){b?this.IsPlaying()?(this.W().pause(),this.va=!0):this.va=!1:this.va&&(this.v.Ga(this.W()),this.va=!1)}};"use strict";
function W(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.qb=null}
self.Fe=class extends self.vd{constructor(b,a,c){super(b,a,c);this.s=null;this.dc=d=>this.Kc(d);this.Vc=!0;this.qb=null;this.S=this.fc=this.ic=0;this.fd=1}l(){this.Ea();W(this);this.dc=null;super.l()}Kc(b){this.J||this.va||b.target!==this.qb||(this.I=this.Vc=!0,this.sa=-1,W(this),Nb(this.v,"ended",this.na,this.Ub))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Vc}qc(){return!this.s||this.I?!0:this.O()}Ra(){let b;b=this.J?this.S:this.fc+(V(this)-this.ic)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.xa=!1;this.fd=1;U(this,a);W(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ha;this.s.connect(this.G);this.qb=this.s;this.s.onended=this.dc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Vc=!1;this.Y=b;this.la=1;this.ic=V(this);this.fc=c}Ea(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.sa=-1}ob(){this.J||this.I||this.O()||(this.S=this.Ra(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Ob(){!this.J||this.I||this.O()||(W(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.dc,this.s.loop=this.Y,U(this,this.Oa),this.Ia(),this.s.start(0,this.S),this.ic=V(this),this.fc=this.S,this.J=!1)}wc(){return super.wc()*this.fd}Tb(){this.fd=this.xa||this.Nb()?0:1;U(this,this.Oa)}zc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ia(){let b=this.la;this.ad&&(b*=this.v.mc);this.s&&(this.s.playbackRate.value=b)}yc(b){this.I||this.O()||(this.J?this.S=b:(this.ob(),
this.S=b,this.Ob()))}xc(){return this.S}Ac(b){b?this.IsPlaying()?(this.va=!0,this.S=this.Ra(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.va=!1:this.va&&(W(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.dc,this.s.loop=this.Y,U(this,this.Oa),this.Ia(),this.s.start(0,this.S),this.ic=V(this),this.fc=this.S,this.va=!1)}Ic(b){super.Ic(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.v=b;this.g=b.V();this.Yd=-1;this.T=this.ld="";this.o=null}l(){this.g=null}N(){}U(){}kb(){return{type:this.T,tag:this.ld,params:this.o}}}
self.ve=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}l(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.te=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.Db=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.ub=X(this);this.ub.gain.value=c;this.A.connect(this.Db);this.A.connect(this.h);this.Db.connect(this.i);this.Db.connect(this.X);this.X.connect(this.ub);this.ub.connect(this.Db)}l(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.Db.disconnect();
this.X.disconnect();this.ub.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.jb.yd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);Y(this,this.ub.gain,e(a),c,d);break;case 5:this.o[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.se=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Pd=this.Od="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.tb=this.g.createConvolver();this.tb.normalize=c;this.tb.buffer=a;this.A.connect(this.tb);this.A.connect(this.h);this.tb.connect(this.i)}l(){this.A.disconnect();this.tb.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}kb(){const b=super.kb();b.bufferOriginalUrl=this.Od;b.bufferUrl="";b.bufferType=this.Pd;return b}};
self.we=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.wb=X(this);this.wb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.wb);this.wb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.wb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,Y(this,this.wb.gain,a/100,c,d)}}};
self.ye=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.xe=class extends Z{constructor(b,a){super(b);this.T="gain";this.o=[a];this.m=X(this);this.m.gain.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){const e=self.jb.yd;switch(b){case 4:this.o[0]=e(a),Y(this,this.m.gain,e(a),c,d)}}};
self.Ae=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.m=this.g.createStereoPanner();this.m.pan.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,Y(this,this.m.pan,a,c,d)}}};
self.Be=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.m=X(this);this.m.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.m.gain);this.C.start(0)}l(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;Y(this,this.m.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.ze=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Ib=X(this);this.Ib.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Ib.gain);this.C.start(0);this.A.connect(this.Ib);this.A.connect(this.h);this.Ib.connect(this.i)}l(){this.C.stop(0);this.C.disconnect();this.Ib.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.ue=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.A=X(this);this.kc=X(this);this.jc=X(this);b=d;.01>b&&(b=.01);this.kc.gain.value=b;this.jc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.nc=this.g.createWaveShaper();this.Qc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Qc[32768+e]=f,this.Qc[32768-
e-1]=-f;this.nc.curve=this.Qc;this.A.connect(this.kc);this.A.connect(this.h);this.kc.connect(this.nc);this.nc.connect(this.jc);this.jc.connect(this.i)}l(){this.A.disconnect();this.kc.disconnect();this.nc.disconnect();this.jc.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.re=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
self.qe=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.Vd=new Float32Array(this.m.frequencyBinCount);this.je=new Uint8Array(a);this.he=this.cb=0;b=this.v;b.Ua.add(this);T(b)}l(){this.v.Ua.delete(this);this.m.disconnect();super.l()}Fa(){this.m.getFloatFrequencyData(this.Vd);this.m.getByteTimeDomainData(this.je);const b=this.m.fftSize;let a=this.cb=0;for(var c=0;c<b;++c){let d=(this.je[c]-
128)/128;0>d&&(d=-d);this.cb<d&&(this.cb=d);a+=d*d}c=self.jb.Me;this.cb=c(this.cb);this.he=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
